### ISSUE TITLE
bee drops two stingers 1.20.1

### ISSUE THREAD

**Issue by Aceplante** [TelepathicGrunt/Bumblezone#327] opened 2024-01-04 07:51 UTC
title, I feel like it should only drop one at a time, and not 100% of the time

**Comment by TelepathicGrunt** [comment] 2024-01-04 12:00
What modloader and Bumblezone version? What other mods did you have on or what modpack are you playing on? Is this a vanilla bee or not? Did the bee have a stinger on or not? (It’s supposed to be a 100% drop rate if bee has stinger and 0% if no stinger)

**Comment by Aceplante** [comment] 2024-01-06 00:56
Yes it was a vanilla bee. It did not sting me so it wouldve had a stinger, I was not using looting and dont think I had any other loot boosting effects,

Yea I checked the loot table and that does seem to be the case, so this may just be me

**Comment by TelepathicGrunt** [comment] 2024-01-06 00:58
I still want your modpack if you are using latest bumblezone version and still experience the issue. A mod could be rolling a second separate loot table for bee death instead of adding their stuff to the bee loot table. My code could then be triggered twice as a result of the other mod rolling the entirely separate loot table

**Comment by Aceplante** [comment] 2024-01-06 00:59
Sure, Ill test it on a minimal instance, just a sec

**Comment by Aceplante** [comment] 2024-01-06 01:06
Ah, yep. It does not happen on a minimal instance, so Ill have to do more testing. You can close for now if you want, ill reopen if i find it

**Comment by TelepathicGrunt** [comment] 2024-01-06 02:13
I like to keep issue reports open and marked with the problematic mod so others can come here and see the cause. It'll also help me as I can see if I can do anything to avoid the other mod's loot table or contact the other modder.

**Comment by TelepathicGrunt** [comment] 2024-01-15 20:13
checking in, any luck? or link to the modpack you're using?

**Comment by TelepathicGrunt** [comment] 2024-01-24 00:02
closing as no new info on what mod could be cause

**Comment by Aceplante** [comment] 2024-01-24 05:47
Good news: https://github.com/Daripher/Auto-Leveling/issues/29

**Comment by TelepathicGrunt** [comment] 2024-01-24 10:37
Reopening

https://github.com/Daripher/Auto-Leveling/blob/1a82e000dd4f82dfbedfe372d1ca5afeaac44ba2/src/main/java/daripher/autoleveling/event/MobsLevelingEvents.java#L107

Idea: mark the bee as drops done somehow so future rolls of loot table doesn’t drop item? Worry it could get accidentally triggered by drop scanning mods

**Comment by TelepathicGrunt** [comment] 2024-01-30 03:07
Should be fixed now. What I do is I attach a temporary data to the entity when I rolled my loot table. Then check if entity was already marked before trying to roll it again and don't if so. This will stop any mod that is erroneously spawning mod loot table drops outside of Global loot Modifier system from causing me to do duplicate drops as well.

**Closed as completed by TelepathicGrunt** 2024-01-30 03:07 UTC
Labels: Mod Compat
