### ISSUE TITLE
Game wouldnt let me load into a world that worked previously

### ISSUE THREAD

**Issue by Crykenpie** [TelepathicGrunt/Bumblezone#140] opened 2022-09-16 23:09 UTC
Apparently the modpack it was in had an issue with thebumblezone, shown in the latest.log so I had to remove it for the modpack to work, and i was told to report it to the mod author. so here is the latest.log, the mc version is 1.19, and its fabric.

here's a link to the log: https://mclo.gs/gR9ltnI

**Comment by TelepathicGrunt** [comment] 2022-09-16 23:16
this is a duplicate of this issue report: https://github.com/TelepathicGrunt/Bumblezone/issues/136

Simply put, the issue is not Bumblezone. Bumblezone is setup correctly and properly in regards to the noise setting json file which mc is the one to parse. The issue is BcLib has a bug where they are messing up when the game parses dimensions and is doing it before the game parses the noise settings files or something. 

You can remove bumblezone or remove bclib. either one should fix the issue until BcLib fixes the issue on their side. There's nothing I can do on my end. 
https://github.com/quiqueck/BCLib/issues/44

**Closed as completed by TelepathicGrunt** 2022-09-16 23:16 UTC
Labels: duplicate
