### ISSUE TITLE
Crashed When Using Ender Peral on Hive

### ISSUE THREAD

**Issue by ChosenArchitect** [TelepathicGrunt/Bumblezone#304] opened 2023-11-11 17:35 UTC
**Issue**
Through an ender pearl onto a Bee hive and it Crashed

**Crash Log**
[crash-2023-11-11_11.31.30-client.txt](https://github.com/TelepathicGrunt/Bumblezone/files/13326084/crash-2023-11-11_11.31.30-client.txt)

**Forge Version**
- Forge - 47.1.3
**Minecraft Version**
- 1.20.1
**Mod Version**
- the_bumblezone-7.0.28+1.20.1-forge.jar

**Comment by TelepathicGrunt** [comment] 2023-11-11 17:48
Duplicate of https://github.com/TelepathicGrunt/Bumblezone/issues/300

Simply put, update your forge version as I used the new hit result for forge’s pearl hit event. Upgrade to v47.1.4 or to 47.2.0+

next Bumblezone version will cap the forge version properly for dependency screen

**Closed as completed by TelepathicGrunt** 2023-11-11 17:48 UTC
Labels: duplicate

**Comment by ChosenArchitect** [comment] 2023-11-11 19:13
I am in the same situation ATM9 is in where the forge version is kinda stuck for us pack devs in 1.20.1 due to issues with a tone of other mods not being compatible with current/latest forge versions. I was hoping to add the mod to my packs but sad I won't be able to. Thanks for the quick response :D

**Comment by TelepathicGrunt** [comment] 2023-11-11 20:33
@ChosenArchitect You don’t have to go straight to latest forge. Just the update after v47.1.3 should work. Test with v47.1.4. 

Also, notify modders to change their version requirements to be “[47.1.0,47.1.4],[47.1.43,)” if they simply are trying to avoid the forge versions that were crashy/problematic

I can try and undo the hit result change in future update to allow 47.1.3 but modders should be notified that 47.1.43+ should be stable-ish now as Lex undid a lot of his broken changes to forge

**Comment by TelepathicGrunt** [comment] 2023-11-11 23:13
Just released v7.0.29 that now allows version 47.1.3 Forge again. I reverted the usage of the new projectile hit event result that was added in Forge 47.1.4.

**Comment by TelepathicGrunt** [comment] 2023-11-12 00:16
Also, just fyi, if you have Cyclic on in modpack, set both `potion_list` set to blank and `harmful_potions` set to false in Cyclic's config. Cyclic has a bug that cause deadlock worldgen or lag game. Just is more noticeable with Bumblezone on but can happen in any dimension. Changing their config will stop the current problematic anti beacon code from running at all with the consequence of making the block no longer remove status effects

**Comment by TelepathicGrunt** [comment] 2023-12-19 13:30
@ChosenArchitect Coming back to this to double check. Bumblezone loads and teleports just fine in both Forge 47.1.3 and in Forge 47.2.17 in 1.20.1 MC. Seems fine to me currently

**Comment by ChosenArchitect** [comment] 2023-12-20 13:33
I should definitely now try and see if it works now that I'm able to switch to the current version of forage for 1.20.1! Finally I was able to update everything!
