### ISSUE TITLE
Teleportation bug

### ISSUE THREAD

**Issue by minatoast** [TelepathicGrunt/Bumblezone#108] opened 2022-02-28 20:21 UTC
When I tried to leave the Bumblezone by falling into the void, it teleported me back to my spawn in the Bumblezone. Super weird. i tried again a second time and it worked. I wonder what caused it.

**Comment by TelepathicGrunt** [comment] 2022-03-02 02:17
I just tested with a new world with `the_bumblezone_forge-4.3.6+1.18.1.jar` bumblezone. I entered the dimension and then exited it just fine. Did you enter the dimension with an older version of bumblezone or entered by piston pushing in single player?

**Comment by TelepathicGrunt** [comment] 2022-03-12 00:45
Gonna close this as I cannot reproduce the issue and havent gotten anymore info over 10 days

**Closed as completed by TelepathicGrunt** 2022-03-12 00:45 UTC
Labels: Need more info
