### ISSUE TITLE
[1.20.1] Chat keeps getting spammed with "check out Bumblezone's advancement tab!"

### ISSUE THREAD

**Issue by Gbergz** [TelepathicGrunt/Bumblezone#293] opened 2023-11-02 14:32 UTC
Title ^

No config to turn this off either (that I've seen).

Image:
![screen](https://github.com/TelepathicGrunt/Bumblezone/assets/26634554/906deeac-d65f-4116-9e56-cdf75ec693bd)

**Versions:**
MC: 1.20.1
Forge: 47.1.3
Bumblezone: 7.0.26

**Comment by TelepathicGrunt** [comment] 2023-11-02 14:34
Can you please be more descriptive? This should only show up once ever for a single user and no one else should be able to see it. Are you playing in multiplayer? Singleplayer? Is it happening every time you approach a beehive? Staying near a beehive?

**Comment by Gbergz** [comment] 2023-11-02 14:48
It's in singleplayer, also in multiplayer, happens everytime I approach any hive, if its from Productive Bees or a vanilla doesn't matter, if I keep standing beside it, or closeby it keeps spamming chat.

**Comment by TelepathicGrunt** [comment] 2023-11-02 14:56
Do you have a mod that is disabling advancements? The way this work is when you get near a beehive, I send that message and complete the first advancement for bumblezone. Once that advancement is completed, the message checks for that completion and does not send message again. 

So if you have a mod that disables advancements, remove said mod because it both breaks this check of mine and completely ruins bumblezone's entire discoverability and progression including the bee queen advancement rewards.

**Comment by TelepathicGrunt** [comment] 2023-11-02 15:03
And please let me know if you are running a mod that disables advancements so I know it is caused by that

**Comment by Gbergz** [comment] 2023-11-02 15:06
I don't have a mod that disables advancements (that I know of anyways), and what mod would do such a thing so I can know? Modlist is TNP Limitless 7 if you're curious, check modlist here, scroll down: https://legacy.curseforge.com/minecraft/modpacks/tnp-limitless-7/files/4819624

Edit: Bumblezone is currently not in the release version of the modpack, planning on adding it next version.

**Comment by TelepathicGrunt** [comment] 2023-11-02 15:30
Recipe Advancement Nuker has an option to disable all advancements iirc but you don't have the mod.

I downloaded Limitless-7-0.28.0.zip and then put on Bumblezone and testing standing near beehives and leaving and coming back. I only got the welcome message once. The advancement the message checks for was completed just fine.
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/64ad89ec-6ae4-4a72-903d-fdd7204c6270)
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/2377594b-ac73-4a3e-8070-03bc36bd1d02)

I'll still add a check in v7.0.27Bumblezone to make the message more resilient to not show up multiple times if advancement is missing. Still not sure why the advancement works for me and you unless you're testing on an unreleased TNP that has changes that led to the advancements breaking/not being parsed/or disabled. You can export your modpack and world by google drive or dropbox (set sharing to enable) or send me your log after having the issue in hopes that the latets.log has more info of what happened to the advancement

**Comment by Gbergz** [comment] 2023-11-02 15:38
Interesting, well only thing I can remember **now** is that I muted the advancement "is_near_beehive" from showing up in chat with Paxi, would that actually mess it up and spam it? 

And yes, I should've mentioned this earlier but I totally forgot I've done this.

![screen](https://github.com/TelepathicGrunt/Bumblezone/assets/26634554/2ee240bd-acba-46be-b7d2-48cdead18a5b)

Could settings show_toast & announce_to_chat to false cause it?

**Comment by TelepathicGrunt** [comment] 2023-11-02 15:41
turning show toast to false should be fine as the check just sees if the advancement is done. 
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/f0a1c9eb-afd6-466d-9959-55ce906a9b77)

Is the criteria still the same or was any other change done to that advancement or the root advancement?

**Comment by Gbergz** [comment] 2023-11-02 15:43
Criteria is still the same, only changed `show_toast` to false from true. `\the_bumblezone\advancements\teleportation\is_near_beehive.json` through a paxi datapack.

**Comment by TelepathicGrunt** [comment] 2023-11-02 15:50
can you share your latest.log? Advancements that fails to be parsed will be logged in there. I can add a config for the chat message to be disabled as well

**Comment by Gbergz** [comment] 2023-11-02 15:57
Sure, hold on. I tested removing the datapack with the change I made through paxi. It doesn't spam anymore.
Then re-adding it spams chat again while near hives.

Here's latest.log: https://gist.githubusercontent.com/Gbergz/b1052ef472274ff79ecb843243f61264/raw/8d305664caa9d18aeaece6b04afaadc052a1c8d7/gistfile1.txt

**Comment by TelepathicGrunt** [comment] 2023-11-02 16:06
Yeah your datapack is unabled to be parsed. It's breaking an advancement which is killing all of the bumblezone advancements 
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/b4545f95-17d6-456e-b039-81fb9c5a0d4a)

It is saying
```[02Nov2023 16:52:12.599] [Render thread/ERROR] [net.minecraft.advancements.AdvancementList/]: Couldn't load advancement the_bumblezone:teleportation/is_near_beehive: Task Advancement{parentId=the_bumblezone:the_bumblezone/root, display=net.minecraft.advancements.DisplayInfo@f5d46ac, rewards=AdvancementRewards{experience=2, loot=[], recipes=[], function=net.minecraft.commands.CommandFunction$CacheableFunction@b8e8e67}, criteria={is_near_beehive=net.minecraft.advancements.Criterion@57a73012}, requirements=[[is_near_beehive]], sends_telemetry_event=false}```

`parentId=the_bumblezone:the_bumblezone/root` seems to be the issue. That's the old 1.19.4 and older parent. It should be `"parent": "the_bumblezone:root"` in 1.20.1+.
https://github.com/TelepathicGrunt/Bumblezone/blob/568b5964b8cbed351279c4bdc7ac3b2ca2d2961b/common/src/main/resources/data/the_bumblezone/advancements/teleportation/is_near_beehive.json#L2

Fix that and check the link i gave to make sure rest of the file is all good. Then try again and the advancements should be parsed without issue

**Comment by Gbergz** [comment] 2023-11-02 16:17
Huh, well there you go, I will adjust this and see how it goes!

**Comment by Gbergz** [comment] 2023-11-02 16:17
Thanks a bunch.

**Comment by Gbergz** [comment] 2023-11-02 16:33
All fixed now, thanks again for the help. Appreciated!

**Comment by TelepathicGrunt** [comment] 2023-11-08 11:35
this should be fixed in new bumblezone version and has config to turn off message now

**Closed as completed by TelepathicGrunt** 2023-11-08 11:35 UTC
Labels: bug
