### ISSUE TITLE
Mixin crash involving the Beehemoth

### ISSUE THREAD

**Issue by Sunconure11** [TelepathicGrunt/Bumblezone#143] opened 2022-09-28 08:29 UTC
https://gist.github.com/Sunconure11/2875a11cba4b329190daf83826c54442

**Comment by TelepathicGrunt** [comment] 2022-09-28 11:27
This crash does not seem to be on Bumblezone end. It appears Allium Peripherals has a mixin that is trying to inject into my entity and I have no idea why they are doing so. 

`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method onChatMessage(Lnet/minecraft/class_2797;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in allium_peripherals.mixins.json:ChatMixin from mod allium_peripherals failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap allium_peripherals-refmap.json`

You can disable that mod for now while I reach out to the dev and see what they say. They might know what the problem is.

**Comment by Sunconure11** [comment] 2022-09-28 11:29
https://github.com/hugeblank/allium-peripherals/issues/16#issuecomment-1260704372

**Comment by TelepathicGrunt** [comment] 2022-09-28 11:32
Oh well that explains it lol. I'll close this then since they have not released a jar for 1.19.2

**Closed as completed by TelepathicGrunt** 2022-09-28 11:32 UTC
Labels: Another mod's issue
