### ISSUE TITLE
bee queen gives too many essences

### ISSUE THREAD

**Issue by kaboom24** [TelepathicGrunt/Bumblezone#445] opened 2024-09-27 03:24 UTC
whenever you complete the whole questline she gives you three essences not one

**Comment by TelepathicGrunt** [comment] 2024-09-27 03:26
Please give me more info. What Minecraft version. What modloader. Are you on server on client.

**Comment by TelepathicGrunt** [comment] 2024-09-27 20:09
Tested singleplayer Neoforge 1.21.1 and Fabric 1.20.1. In both cases, I get 1 Essence of the Bees. Therefore, I need you to give me more info to even go on and what modpack you are using. Otherwise, I'll close this issue report in a week as unreproducable and not enough info to go on.

**Comment by kaboom24** [comment] 2024-09-28 23:35
mc version is 1.20.1 modloader is forge not neoforge singleplayer so I dont think that means server here is the modpack
[alexs caves.zip](https://github.com/user-attachments/files/17176894/alexs.caves.zip)

**Comment by TelepathicGrunt** [comment] 2024-09-29 12:09
Using your modpack, I only got 1 Essence of the Bees result
![image](https://github.com/user-attachments/assets/e07aa2c8-2a4d-4495-ac5a-bf4a5dbab157)


I loaded your pack, ran `/advancement grant @s through the_bumblezone:the_queens_desire/journeys_end`, then right clicked the Bee Queen

Is there anything special you were doing at the time or anything special about your character setup

**Comment by kaboom24** [comment] 2024-09-29 17:04
I am a vampire tier 14 and lord tier 5 but I dont think that makes a diffrence it might just be a bug with my game.

**Comment by kaboom24** [comment] 2024-09-29 23:49
WAIT I THINK I FIGURED IT OUT try spam clicking her when the quests are completed I was holding down right click because I was trading at the same time

**Comment by TelepathicGrunt** [comment] 2024-09-30 00:54
Still gives only 1 when both spam clicking and holding down right click with your modpack. (Speaking of which, spam clicking doesn't make sense to do when holding down right click will trade with less work. Or just dropping the whole itemstack at her feet will trade the entire stack for fastest way)

If you look here:
https://github.com/TelepathicGrunt/Bumblezone/blob/d3125286a94f2d9ca9d7b3cfe12f5a107ec587c1/common/src/main/java/com/telepathicgrunt/the_bumblezone/entities/mobs/BeeQueenEntity.java#L701-L705

This code runs on right click. receivedEssencePrize is a data point saved in the player's capability data point. If receivedEssencePrize is false because Essence of the Bees was not given to the player yet, it'll give it and then set receivedEssencePrize to true. Then the next time this code runs, this if statement will not run the code inside because receivedEssencePrize is true. 

So physically, it can't give the essence of the bees multiple time unless some mod broke the data saving with the capability so it doesn't change receivedEssencePrize to true. Or some mod is running multiple right click code multithreaded in a single click which would be cursed hell and that mod needs to be shot out of a cannon and into the sun.

Either way, I cannot reproduce it and if it is indeed happening for you, it is likely nothing wrong with my code but some other mod and there isn't anything I can do anyway. The capability system is Forge's system and has existed for a long time so any data saving issue within itself for entities would've been found and fixed a long time ago.

**Comment by kaboom24** [comment] 2024-10-01 22:47
k thanks

**Comment by TelepathicGrunt** [comment] 2024-10-08 11:41
Gonna close this on the account of unable to reproduce even with the modpack itself. No one else is reporting or experiencing the bug too oddly enough

**Closed as completed by TelepathicGrunt** 2024-10-08 11:41 UTC
Labels: Need more info
