### ISSUE TITLE
1.19.3 v6.4.10 Bumblezone worlds cannot load in newer 1.19.3 Bumblezone versions without editing level.dat file

### ISSUE THREAD

**Issue by SubSonicEr** [TelepathicGrunt/Bumblezone#184] opened 2023-01-09 17:11 UTC
Hey there,

since Version 6.6.0 of "The Bumblezone" the Mod is breaking all the maps, which are created without this mod such as with this mod with a version below 6.6.0. The error is telling that allegdly the datapack has failed to load of the map but there is no datapack.

If you don't want to loose your map, there is a workaround. You can create a map with the same seed and configs with the version 6.6.+ of the mod and overwrite the "level.dat" of your map. But you will loose all your inventory and skill progress (used with mods) of your character.

Greetings

**Comment by SubSonicEr** [comment] 2023-01-09 17:48
When trying to export the world settings, MC is showing an error that a biome of The Bumblezone is bugged

**Comment by SubSonicEr** [comment] 2023-01-09 17:49
It's the biome thebumblezone:extra_biomes_to_spawn

**Comment by TelepathicGrunt** [comment] 2023-01-09 17:54
@SubSonicEr i though I already tested old worlds and they worked for me as I added changes to try and load old level.dat save files for old Bumblezone data

  I’m going to need more info than what you provided. What Mc version are you on? What modloader, and what Bumblezone version was the old world made in? (And what Mc version was the old world made in too)

also that “biome” is not a biome. It’s a biome tag that is suppose to be optional and can exist or not in the level dat file data. Old worlds do not have it hence why I tried to code it to be optional so old worlds can still load and then later get replaced and updated with the new dimension info later

**Comment by SubSonicEr** [comment] 2023-01-09 20:12
Hey there,

thx for the fast replay. I forgot to tell you the additional info. I'm using MC 1.19.3 with forge. When using "The Bumblezone" with version 6.4.10 everything works fine. I've created my map with version 6.4.10. Using 6.6.0 such as 6.6.1 will break my map. 

I fixed my map with the workaround creating an identical map and overwriting the level.dat. If you need my used mods just tell me. I hope I can help you.

Greetings

**Comment by TelepathicGrunt** [comment] 2023-01-09 23:23
## The real workaround fix: 
Is to delete the Bumblezone dimension entry from the level.dat file. Bumblezone will automatically create the dimension again with the proper data needed. Can be done with NBTExplorer

![image](https://user-images.githubusercontent.com/40846040/211426389-69ea418c-233e-4f46-a208-3aee0be7c1fb.png)

The issue is only specifically about the older pre-6.6.0 1.19.3 Bumblezone worlds. 1.19.2 does not have this issue. 1.19.2 Bumblezone worlds can be loaded just fine into 1.19.3 v6.6.0+ Bumblezone. It is only just v6.4.10 version that is the issue. 

## Technical explanation:
Mojang's parsing of the level.dat file for custom dimension is horrifying awful in every way imaginable. The issue is in v6.4.10 bumblezone, I made a typo in the Biome Source code. The constructor was reading the extra biome spawn info and assigning it to the main biome field and vice versa.  
https://github.com/TelepathicGrunt/Bumblezone/blob/b00b763cdb0b29cda18b7aae3f778ef66518c2c0/src/main/java/com/telepathicgrunt/the_bumblezone/world/dimension/BzBiomeProvider.java#L57

So the #the_bumblezone:extra_biomes_to_spawn entry was being put into the wrong field in the level.dat file.
![image](https://user-images.githubusercontent.com/40846040/211427632-55133217-8ae8-4cca-9413-0d6da074b2fd.png)

That tag was removed and the extra biome field replaced with blob_biomes field. However, old worlds still keeps that #the_bumblezone:extra_biomes_to_spawn tag entry for main_biomes field and the game is flipping out because the #the_bumblezone:extra_biomes_to_spawn tag no longer exists so it cannot pase that entry of level.dat file anymore.

Deleting the entire bumblezone dimension entry from the level.dat file fixes the issue because then the game can recreate that dimension entry from scratch with the proper info.

Still looking into a solution for my mod to bypass this issue entirely but having great difficulty right now.

**Comment by SubSonicEr** [comment] 2023-01-09 23:27
Hey there thx for this solution and the nice contact. With which tool do you edit the level.dat file?

Edit: I was blind. I saw it by myself :D It's NBTExplorer :D

**Comment by TelepathicGrunt** [comment] 2023-01-09 23:29
I use NBTExplorer which can be downloaded here: https://github.com/jaquadro/NBTExplorer/releases

**Comment by SubSonicEr** [comment] 2023-01-09 23:33
Thx again for your help with this issue. I think this will help me in many other problems caused by mods :) Really big thx.

**Comment by TelepathicGrunt** [comment] 2023-02-07 23:27
I'm going to close this now as 6.4.10 bumblezone is so old that I don't think anyone is playing with it anymore so they should not come across this issue anymore

**Closed as completed by TelepathicGrunt** 2023-02-07 23:27 UTC
Labels: bug, help wanted
