### ISSUE TITLE
[Server thread/ERROR]: Unknown structure piece id: minecraft:bigdungeon

### ISSUE THREAD

**Issue by Yourname942** [TelepathicGrunt/Bumblezone#15] opened 2020-08-16 15:27 UTC
**With Bubmlezone Enabled**
latest log: https://gist.github.com/Yourname942/453a7eeee008c1defdeb5b775f9034da

Steps Taken:
1. Select Play in TwitchApp
2. Select Play in Minecraft Launcher
3. Create new world
4. Enter world
5. Exit Minecraft
6. Repeat Steps 1-5 (but now for step 3, enter the world instead of creating new world)

**With Bubmlezone Disabled**
latest log: https://gist.github.com/Yourname942/8e56d20b79afad59a14f3b6063f01ab3

Steps Taken:
1. Select Play in TwitchApp
2. Select Play in Minecraft Launcher
3. Create new world
4. Enter world
5. Exit Minecraft

Minecraft 1.15.2
Forge 31.2.36
The Bumblezone (forge) 1.3.10

Note:
A) I encountered this error when I created world 1 (ie. a new world)
B) I tried to recreate this issue by deleting the previous world, and then repeating the process (steps 1-5) 
    - result: I did not see the error until I exited Minecraft (step 5), relaunched Minecraft, and then reentered the world.

**Comment by TelepathicGrunt** [comment] 2020-08-16 15:38
This does not seem to be a Bumblezone issue but another mod's issue. Someone is probably not registering their dungeon properly or something. Even worst, this person registered their piece under the Minecraft namespace which is a big nope.

Your bets best is to try and find who's mod "minecraft:bigdungeon" belongs to and give them this bug report. The issue is, idk who it might be.

**Comment by TelepathicGrunt** [comment] 2020-08-16 15:40
Oh it looks like it's Quark and someone has opened an issue with them as well
https://github.com/Vazkii/Quark/issues/2410

**Comment by Yourname942** [comment] 2020-08-27 14:53
Thank you for the replies, I'm glad it may not be an issue on your end.

**Comment by TelepathicGrunt** [comment] 2020-08-28 00:39
Yeah. Vaskii found it is caused by a crash with BetterAnimal being on with Quark here: https://github.com/Vazkii/Quark/issues/2410#issuecomment-675651221

I'll close this report now. :)

**Closed by TelepathicGrunt** 2020-08-28 00:39 UTC
Labels: Mod Compat issue, bug
