### ISSUE TITLE
Insta Crashing when joining the server.

### ISSUE THREAD

**Issue by OrkeChill** [TelepathicGrunt/Bumblezone#422] opened 2024-07-19 20:41 UTC
AOF 7 people said to come here, I were playing AOF7 for like 2months, went to bumblezone and game instantly crashed, after that when I start server it starts but when I enter it instantly crashes, I don't know why, I would really appreciate some help.
[crash-2024-07-19_23.19.08-server.txt](https://github.com/user-attachments/files/16316908/crash-2024-07-19_23.19.08-server.txt)

**Comment by TelepathicGrunt** [comment] 2024-07-19 20:43
This looks familiar and you are using an outdated Bumblezone. Please update Bumblezone on client and server and see if issue is resolved. Pretty sure I fixed this a while ago

**Comment by TelepathicGrunt** [comment] 2024-07-19 20:54
Closing as duplicate of the stars issue and was fixed a while ago in an AOF7 update

**Closed as completed by TelepathicGrunt** 2024-07-19 20:54 UTC
