### ISSUE TITLE
Incense candle black texture

### ISSUE THREAD

**Issue by CreativeManul** [TelepathicGrunt/Bumblezone#215] opened 2023-02-25 13:08 UTC
Incense candle have black texture and missing texture particles when broken. the_bumblezone_forge-6.6.11+1.19.2

**Comment by TelepathicGrunt** [comment] 2023-02-25 13:29
I cannot reproduce the issue. I placed a bunch of Incense Candles and broke them all and they all looks and work fine. Please give me your entire modpack as it sounds like this is an issue caused by a different mod. Not Bumblezone. But I need to know what mod it is so I can complain to them or mark them as incompatible.

Video of me breaking a bunch of Incense Candles: https://streamable.com/emw1cx

**Comment by CreativeManul** [comment] 2023-02-25 15:51
O!  It seems to be the problem! I don't use optifine, but I use them.
rubidium-0.6.2
RubidiumExtra-1.19.2-0.4.11.44
oculus-mc1.19.2-1.2.8a
dynamiclightsreforged-1.19.2_v1.4.0

Yes, I tested only with them - without them there is no problem!
Only Incense candle. Everyone else is fine!

**Comment by TelepathicGrunt** [comment] 2023-02-25 16:01
Rubidium is that sodium port right? Well, they inherited this sodium bug then. https://github.com/TelepathicGrunt/Bumblezone/issues/176

the solution would’ve been to add this mod but it’s only for Fabric sadly. https://www.curseforge.com/minecraft/mc-mods/unofficial-sodium-biome-blending-fix

You could try and ask Rubidium to include the code that fixes the biome blending or set biome blending to off in the config for that mod

**Comment by TelepathicGrunt** [comment] 2023-02-25 16:03
Closing as I updated that other issue report’s title to mention rubidium is also affected so that issue report handles this biome blending issue with sodium and it’s forks

**Closed as completed by TelepathicGrunt** 2023-02-25 16:03 UTC
Labels: Mod Compat, Need more info
