### ISSUE TITLE
(1.21) Using the Essence of Continuity disables cheats, regardless if they're enabled or not

### ISSUE THREAD

**Issue by Inonedn** [TelepathicGrunt/Bumblezone#403] opened 2024-06-21 18:34 UTC

**Comment by TelepathicGrunt** [comment] 2024-06-21 18:49
? what do you mean by this. I need far more info

**Comment by Inonedn** [comment] 2024-06-21 19:14
When the player is saved from death by it, players who had cheats will lose access to them, i.e a creative mode switching to survival mode

**Comment by TelepathicGrunt** [comment] 2024-06-21 19:24
Ah so changing *gamemodes*. That's very different than commands permission levels which I thought you were trying to say as those higher permission commands are usually called cheats. Also why I couldn't reproduced what you were saying as I was testing in survival

**Comment by TelepathicGrunt** [comment] 2024-06-21 19:33
Actually, how are you even dying in creative? Now I'm still confused on exactly what you're saying. Can you please give me a full reproduction steps for seeing the issue easily? Otherwise, i cannot verify if any changes I do actually address the issue

**Comment by TelepathicGrunt** [comment] 2024-06-22 10:57
Please try v7.4.7 (1.20.1) or v7.6.4 (1.21) and see if this resolves your issue. Sent more packets that vanilla is sending on teleportation. No idea if it solves your issue since I can't reproduce it.

**Comment by TelepathicGrunt** [comment] 2024-06-27 00:23
Any news on this?

**Comment by Inonedn** [comment] 2024-06-28 11:24
It happens when you are in creative and have cheats, and switch to survival mode, then "dying" disables your cheats

**Comment by TelepathicGrunt** [comment] 2024-06-28 12:00
When you say cheats, are you talking like the ability to run commands? And is it actually happening with latest jar? And is this on server or singleplayer?

I’m sorry but please give me more than just vague snippets of info. It’s really difficult for me to follow in your footsteps of what exactly you’re seeing

**Comment by TelepathicGrunt** [comment] 2024-06-28 13:32
Here is what I have done.

Bumblezone v7.6.6 alone in Single Player NeoForge.

- Created world in singleplayer creative mode.
- Enable LAN Mode with allow commands set to true.
- Ran `/debug start` and `/debug stop` to see I have permission to run the command.
- Ran `/enchant @s minecraft:unbreaking 2` on a tool to verify I can enchant stuff.
- Ran `/gamemode survival` to go into survival mode
- Consumed Essence of the Bees item.
- Put Essence of Continuity in my offhand slot.
- Jump off a mountain and get my death prevented and teleported back to my save respawn position.
- Ran `/debug start` and `/debug stop` to see I have permission to run the command. (While in survival)
- Ran `/enchant @s minecraft:unbreaking 2` on a tool to verify I can enchant stuff. (While in survival)
- Ran `/gamemode creative` to go into creative mode
- Found I do indeed still have permission for these commands and no issue at all.

**Comment by TelepathicGrunt** [comment] 2024-07-04 19:43
Closing as cannot reproduce. Reply here with new clear steps and if I can reproduce, I will reopen

**Closed as completed by TelepathicGrunt** 2024-07-04 19:43 UTC
Labels: Need more info
