### ISSUE TITLE
Ticking Entity issue; checkIfCustomFluidIsBreathable?

### ISSUE THREAD

**Issue by flarefluffsune** [TelepathicGrunt/Bumblezone#393] opened 2024-05-22 08:35 UTC
I'm not entirely sure whats going on and I can fix the issue by deleting all mobs from Bumblezone (I can always respawn the queen after all thankfully) but it seems that when bee's touch a liquid it crashes the game and honestly I'm not sure why because I've already spent literal hours in the Bumblezone and nothing in my mod composition has changed since I last entered it. 
I'm only assuming this is an issue with Bumblezone due to the "Custom Fluids" thing.

Here's the log: https://paste.ee/p/9gg5m

```
Time: 2024-05-22 09:27:06
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3610.method_15772()" because the return value of "net.minecraft.class_1309.getTouchingFluid()" is null
	at net.minecraft.class_1309.handler$mea000$star$checkIfCustomFluidIsBreathable(class_1309.java:3165)
	at net.minecraft.class_1309.method_6094(class_1309.java:347)
	at net.minecraft.class_1309.handler$mok000$the_bumblezone$bumblezone$breathing(class_1309.java:15676)
	at net.minecraft.class_1309.method_5670(class_1309.java:467)
	at net.minecraft.class_1308.method_5670(class_1308.java:284)
	at net.minecraft.class_1297.method_5773(class_1297.java:474)
	at net.minecraft.class_1309.method_5773(class_1309.java:2380)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at net.minecraft.class_4466.method_5773(class_4466.java:299)
	at net.minecraft.class_3218.observable$track(class_3218.java:22254)
	at net.minecraft.class_3218.redirect$ipd000$observable$onTickNonPassenger(class_3218.java:22270)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by TelepathicGrunt** [comment] 2024-05-22 09:53
Duplicate of the pinned issue: https://github.com/TelepathicGrunt/Bumblezone/issues/390

More details in that issue report of what the issue is and the problematic mod

**Closed as completed by TelepathicGrunt** 2024-05-22 09:53 UTC
Labels: duplicate

**Comment by flarefluffsune** [comment] 2024-05-22 16:52
Alright sorry.
