### ISSUE TITLE
 Random Crashes on 1.19.2

### ISSUE THREAD

**Issue by pokesmells** [TelepathicGrunt/Bumblezone#211] opened 2023-02-22 10:20 UTC
Hello there! So I've been getting random crashes with your mod when this error occurs
"Failed to deserialize component: unregistered key the_bumblezone:player_component"

Initially thought it was because of Lithium or Sodium issues, but the devs from there told me it was a mod doing unsafe multithreading into chunk loading.

Now I thought this was a fluke, but this has happened twice now, with the same error and then a crash.

Legitimately have no clue what's going on or if it's even your mod, but I'll try and provide as much info as possible to understand what's happening.

First I got exit code -805306369, then I got exit code -1, I have both logs and crash logs which I'll attach, and to add, I do not have Optifine or Optifabric, I do have CIT Resewn, CEM, Animatica, and Transparent for some texture packs, which affect items.

Mod Version: the_bumblezone_fabric-6.6.10+1.19.2.jar

Fabric Version: 0.14.14 - fabric-api-0.73.2+1.19.2

At the time of writing this, I see there is an update, I have no seen if I encounter such a crash on the latest, but will not do so for now.

[2023-02-21-2.log](https://github.com/TelepathicGrunt/Bumblezone/files/10802493/2023-02-21-2.log)
Latest.log of first crash
[crash-2023-02-21_11.43.45-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/10802500/crash-2023-02-21_11.43.45-server.txt)
First crash log

[latest.log](https://github.com/TelepathicGrunt/Bumblezone/files/10802515/latest.log)
Second latest.log of second crash
[crash-2023-02-21_16.17.20-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/10802521/crash-2023-02-21_16.17.20-server.txt)
Second crash log

**Comment by TelepathicGrunt** [comment] 2023-02-22 12:33
Few things to note here. 

Like I mentioned in https://github.com/TelepathicGrunt/Bumblezone/issues/196 over someone asking about the player component: 

> that's just means a component on the player wasn't able to be read. player_component does not exist in my codebase ever since 1.18+. I am assuming this is an old world from 1.17 or older you ported to a newer mc version because the player had an old component name that was later replaced. The old data wont be able to be read anymore.
> 
> There is no issue that will be caused by the old data being unabled to be parse by Cardinal Components as they simply just skip the old data and log it's presence. That's all. Because the components now are entity_component, original_flying_speed, neurotoxins_missed_counter, essence_component, misc_component and those are created automatically on the player and will be read just fine.

With that out of the way, I do not see anything here that even mentions Bumblezone and so I highly doubt this is a Bumblezone issue. Plus my mod generates chunks the same way vanilla does with the Chunk Generator so there's no fancy multithreading stuff going on beyond what vanilla already does.

All I see is the first crash is caused by Lithium and the second crash is caused by VMP-fabric. both crashed on trying to keep track of what entities load and unload so I don't see how Bumblezone plays into that at all. Instead, Lithium and VMP-fabric may not be compatible with each other. Or incompatible with another mod that affects entity spawning/despawning or chunk loading/unloading or something like that. You'll have to binary search or remove mods until you find the root cause.

Going to close this until something comes up that does point to Bumblezone as being involved.

**Closed as completed by TelepathicGrunt** 2023-02-22 12:33 UTC
Labels: Another mod's issue
