### ISSUE TITLE
Progressive Bosses's Elder Guardian enable attack config option causes Calming Essence fight to freeze

### ISSUE THREAD

**Issue by kaboom24** [TelepathicGrunt/Bumblezone#303] opened 2023-11-10 02:20 UTC
as in one of my previous issues I mentioned that every time a get close to beating the calm trial it freezes permanently but never crashes so I cant send a crash log and you said to send you my modpack I dont know how to do that the modloader is forge and I do am playing singleplayer could you let me know how tosend you my custom modpack oh and one more thing in the green sanctum you can just throw your own dirt pellets you dont have to hit them back

**Comment by TelepathicGrunt** [comment] 2023-11-10 10:59
After you reproduce the issue, you can still send me the latest.log file from the logs folder above the mods folder. This might hold an error message that I can read.

As for sharing your modpack with me using the CurseForge Launcher, here are the steps to do that:

1. Right click on the modpack instance. And click "Export Profile".
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/e412f071-d522-4e55-82d1-7d1e12890319)

2. Select the files you want to export. Do not select Saves as that will make the export massive in size and harder to share with me. Then click "Export" and save the exported profile to somewhere you can access.
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/96d69fde-658b-4da0-b258-5d31634470c0)

3. Then drag and drop the exported profile into the comment box on GitHub here. It will be automatically attached to your comment as an attachment for me to download and run your modpack.
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/7054175d-1042-4435-96f5-a3de84572fa4)

**Comment by kaboom24** [comment] 2023-11-10 21:11
here is the file modpack and I will work on figuring out how to send you the latest.log file
[alexs caves.zip](https://github.com/TelepathicGrunt/Bumblezone/files/13323223/alexs.caves.zip)

**Comment by kaboom24** [comment] 2023-11-10 21:12
oh wait found it
[latest.log](https://github.com/TelepathicGrunt/Bumblezone/files/13323225/latest.log)

**Comment by kaboom24** [comment] 2023-11-10 21:13
one more thing I know I reproduced the issue but it was a while ago will that affect anything and does it need to be with the game open?

**Comment by TelepathicGrunt** [comment] 2023-11-12 00:47
I reproduced the issue with your modpack. The freeze is happening when the Guardian spawn bubbles. A mod in your pack must be doing something bad with particles to break even vanilla mobs spawning bubbles on client side. I'll keep poking to find 
who is the cause

Edit. I might have a clue of what's going on. Might be a strange side effect of having the guardian stay locked on player

**Comment by TelepathicGrunt** [comment] 2023-11-12 01:00
I am 99% certain the bug is caused by progressivebosses due to this mixin
https://github.com/Insane96/ProgressiveBosses/blob/4515f4a22f965f25e5bdc4dab88907f347742cca/src/main/java/insane96mcp/progressivebosses/mixin/ElderGuardianMixin.java#L15

**Comment by TelepathicGrunt** [comment] 2023-11-12 01:24
Workaround for now is to set this Progressive Bosses's "Enable Attack" config to false for Elder Guardians 
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/6c576767-af14-4747-a1a7-780395c5fa43)

**Comment by kaboom24** [comment] 2023-11-12 05:08
thanks

**Comment by TelepathicGrunt** [comment] 2023-11-13 12:07
Just tested ProgressiveBosses-3.9.5-mc1.20.1.jar that was recently released and the freeze is fully fixed now by them!

**Closed as completed by TelepathicGrunt** 2023-11-13 12:07 UTC
Labels: Another mod's issue
