### ISSUE TITLE
Illagers+ mod caused bumblezone dimension to freeze/deadlock/crash

### ISSUE THREAD

**Issue by RitzScythe** [TelepathicGrunt/Bumblezone#85] opened 2021-10-15 16:15 UTC
Crash when going into bumble zone can provide whatever additional info needed. 

[latest.log](https://github.com/TelepathicGrunt/Bumblezone/files/7354633/latest.log)
[debug.log](https://github.com/TelepathicGrunt/Bumblezone/files/7354634/debug.log)
[crash-2021-10-14_21.09.20-client.txt](https://github.com/TelepathicGrunt/Bumblezone/files/7354637/crash-2021-10-14_21.09.20-client.txt)

**Comment by TelepathicGrunt** [comment] 2021-10-16 01:08
Can you send me your modpack or zipped up mod folder so i can test and see if I can reproduce the issue? The crash-2021-10-14_21.09.20-client.txt shows immersive engineering but when testing that mod with bumblezone, I get no crash.

**Comment by RitzScythe** [comment] 2021-10-16 01:16
[Asagia Realms-v0.0.5REDUX.zip](https://github.com/TelepathicGrunt/Bumblezone/files/7356517/Asagia.Realms-v0.0.5REDUX.zip)
idk if this is what you want but if this doesnt work its on curseforge, its the latest version of Asagia Realms

Thank you very much by the way!

**Comment by TelepathicGrunt** [comment] 2021-10-16 02:19
So your server may be deadlocking and crashing as a result of being stuck. When testing myself, the dimension froze and when i did a thread dump to find out what code was running, it was [Pirates And Looters Kraken Update mod](https://www.curseforge.com/minecraft/mc-mods/pirates-and-looters-mod)'s code. Whatever code that mcreator mod was running, it is not safe world worldgen I'm guessing. Upon disabling the mod, the deadlock went away. Remove that mod and see if that fixes the issue for you. Sadly, it seems the dev for that mod isn't responding to comments on their modpage

**Comment by RitzScythe** [comment] 2021-10-16 03:28
so im trying on a single player world, and removing it stops the crash, but the world gen is still stalled. only a small number of rendered are chunks and things like entities are frozen. Could do /spawn to get back to overworld with no crash though

**Comment by RitzScythe** [comment] 2021-10-16 03:47
are we sure it wasnt illagers+ because I tried a new world and there was an archer outpost from that mod in the bumblezone. 

Removed both and it seems to fix it, illagers are still in the already generated area of bumblezone but no new stuff and it no longer stalls

**Comment by TelepathicGrunt** [comment] 2021-10-16 11:28
I saw the illagers+ structure but it didn't stall for me when i kept that on. But good to know it was both of those mods. Thank you for letting me know! It looks like illagers+ has a config with a dimension blacklist for their structures so you can add bumblezone dimension to their blacklist and keep their structures out of my dimension

**Comment by TelepathicGrunt** [comment] 2021-10-16 12:22
Oh sorry. After you mentioned Illagers+, I re-looked at it and I think it may just be Illagers+. Not the pirates mod.

See the lighting thread dying in the logs in my test with Illagers+ and Bumblezone?
https://paste.ee/p/835L6

So funny thing about the minecraft lighting system. It's bad.
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4870

Specifically, if a structure replaces an full 16x16x16 chunk section that contained a light block, the lighting system crashes which causes the server to wait on the dead lighting thread forever and deadlocks. The AE2 devs found a fix which is this mixin
https://github.com/TelepathicGrunt/WorldBlender-Fabric/blob/latest-released/src/main/java/com/telepathicgrunt/worldblender/mixin/dimensions/LightingProviderMixin.java

Illagers+ should add this mixin too so that their structures does not deadlock in other dimensions including overworld. I'll let them know so they can try and add the fix into their mod! Hopefully they will respond soon!

**Comment by TelepathicGrunt** [comment] 2021-10-25 22:15
illagers_plus-1.16.4v1.7 update fixes this incompat now. So updating Illagers+ should work. I'll close this issue report now.

**Closed as completed by TelepathicGrunt** 2021-10-25 22:15 UTC
Labels: Mod Compat
