### ISSUE TITLE
Crystalline Flower not giving enchantments past a certain number of enchants in the list

### ISSUE THREAD

**Issue by gonggong666** [TelepathicGrunt/Bumblezone#236] opened 2023-04-08 17:57 UTC
It won't allow the enchantments past mcdw:recycler for example.
Enchantments are sorted in alphabetical order, and anything past a given enchant(**varies per modpack**) on the list doesn't go through.

**Comment by TelepathicGrunt** [comment] 2023-04-08 18:02
@gonggong666 I need far more information please. 

1) What Bumblezone version are you using and for what MC version and mod loader? I fixed an issue a while ago already where on servers, modpacks with too many enchantments would not sync properly to client screen. (Fixed in v6.7.0 but I always recommend latest version of my mod)
https://github.com/TelepathicGrunt/Bumblezone/issues/228#issuecomment-1482135902

2) If you are using latest Bumblezone version, are you playing on single player or are you connecting to a server?

3) Specifically what modpacks and their version are you playing on? I need to be able to reproduce the issue myself to even know how to begin debugging.

**Comment by TelepathicGrunt** [comment] 2023-04-08 19:45
Just tested 1.19.2 AoF and I put on MCDW, MCDA, and several other enchantment mods to bloat up number of enchantments. Latest Bumblezone shows all the enchantments just fine in single player.

![image](https://user-images.githubusercontent.com/40846040/230739906-cb5044ff-89e9-42b7-bb32-48b9336795fb.png)
![image](https://user-images.githubusercontent.com/40846040/230739910-bcac6a42-8fd9-45c0-bfb1-55b777f071be.png)

I would suggest making sure Bumblezone is updated for you and if it still has issue, give me the exact modpack you're using and whether the issue is when connecting to server or playing single player

**Comment by TelepathicGrunt** [comment] 2023-04-18 08:57
Closing now as it has been a week with no extra info and I am unable to reproduce issue

**Closed as completed by TelepathicGrunt** 2023-04-18 08:57 UTC
Labels: Need more info
