### ISSUE TITLE
Server Crashes when entering Boss Fight

### ISSUE THREAD

**Issue by MmeCromatique** [TelepathicGrunt/Bumblezone#428] opened 2024-08-06 14:56 UTC
Server Fabric 1.20.1
Mod: 7.4.14

Hello, I'm administrating a modded server and a player is making the server crash when entering in this white thing
![IMG_20240806_160536](https://github.com/user-attachments/assets/c5fe9a75-8deb-4150-90c8-be03f545738b)

I don't know the mod and the player is very vague when describing what he did saying "I entering the white block and it teleported me in a zone" crashing the server.

I had to edit his playerdata to get him back to the overworld and preventing the server from crashing.

Here is the crash report: 
[crash-2024-08-06_14.40.28-server.txt](https://github.com/user-attachments/files/16512024/crash-2024-08-06_14.40.28-server.txt)

I saw similar issue but not the same error, in this case it's `java.lang.NullPointerException: Cannot invoke "java.util.Optional.isPresent()" because "this.apoli$shouldApplyArmor" is null`

**Comment by TelepathicGrunt** [comment] 2024-08-06 16:10
The issue is the Apoli mod within Origins mod. Nothing I can do. An issue report has been made to them https://github.com/apace100/apoli/issues/177

if you can get the devs to fix their code, it should stop crashing my mod. I can’t shield against their problematic code

duplicate of https://github.com/TelepathicGrunt/Bumblezone/issues/292

**Closed as completed by TelepathicGrunt** 2024-08-06 16:10 UTC
Labels: duplicate

**Comment by TelepathicGrunt** [comment] 2024-08-06 16:11
Actually, looks like the apoli issue report was closed as completed. Are you sure you updated Origins mod to the latest version with the fix?

**Comment by MmeCromatique** [comment] 2024-08-06 16:28
We're on Origins 1.10.0, latest version I can see, so yes
The issue has been fixed in a release on Dec 22, 2023, and the latest 1.20.1 Origin version was released on Jun 25, 2023

So I don't think it will be fixed for this version then if the fix is for 1.20.2+

Thank you for your intake, sorry for wasting your time

**Comment by TelepathicGrunt** [comment] 2024-09-10 11:28
I decided to backport Apoli's 1.20.2 fix to 1.20.1 by making a small mixin mod to specifically fix this
https://legacy.curseforge.com/minecraft/mc-mods/origins-apoli-armor-mixin-fix

This will stop the crash with Bumblezone

**Comment by MmeCromatique** [comment] 2024-09-10 20:11
OMG, thank you so much !!! We'll be trying it out tomorrow ! Thank you 😭

**Comment by carrot1703** [comment] 2024-09-11 16:59
Thank you so much ! we've tried it and it works amazingly ! thank you again for your work this mod is amazing we have so much fun while playing it!

**Comment by hika0** [comment] 2024-09-11 17:00
Thank you very much !!!! We have only done two of them for now I still have to explore to do the others but we already had a lot of fun !
