### ISSUE TITLE
[Fabric 1.20.1] Attempting to ride a Beehemoth in the end dimension crashes the server

### ISSUE THREAD

**Issue by dre3002** [TelepathicGrunt/Bumblezone#275] opened 2023-09-30 00:23 UTC
I tried taking the Beehemoth into the end dimension to help with fighting the dragon/finding elytra. I am able to get the Beehemoth into the end dimension, but as soon as I try to ride it the game freezes and then crashes.

I will also add I am playing on the Better MC [FABRIC] 1.20.1 Version: 14 modpack.

**Comment by TelepathicGrunt** [comment] 2023-09-30 00:34
Please give me the latest.log file after the crash. Without the log, I cant do much troubleshooting

**Comment by TelepathicGrunt** [comment] 2023-09-30 02:53
I am able to ride Beehemoth in End dimension with that modpack. Please reproduce the crash again and give me the latest.log file from the logs folder above the mods folder. Seems the issue is more specific to your world
![2023-09-29_22 52 25](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/06baa8b5-170f-4531-8a89-293588fe1ca4)

**Comment by dre3002** [comment] 2023-10-04 00:14
Sorry for the delayed reply. This is interesting though. I have reproduced the crash, here is the requested log file. 
[crash-2023-10-04_00.11.57-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/12797962/crash-2023-10-04_00.11.57-server.txt)

**Comment by TelepathicGrunt** [comment] 2023-10-04 01:17
Fixed in v7.0.13 now released
Thank you for the report!

**Closed as completed by TelepathicGrunt** 2023-10-04 01:17 UTC
Labels: bug
