### ISSUE TITLE
[1.19] Coral Tombstone crashing when tempting Honey Slime

### ISSUE THREAD

**Issue by Silivek** [TelepathicGrunt/Bumblezone#123] opened 2022-07-16 02:32 UTC
I was running a server when the crash happened. I can no longer join the server without it closing immediately. I have no clue what could be causing it besides the fact that the ticking entity is a honey slime.
Forge Version: 41.0.63
Bumblezone Version: 6.0.1+1.19
Crash Report: https://pastebin.com/WhaEBHrp

**Comment by TelepathicGrunt** [comment] 2022-07-16 03:12
Looks like the issue isn't bumblezone. It's caused by this:
`ovh.corail.tombstone.helper.Helper.getBrightness`

Corail tombstone is broken and is calling clientsided code on serverside with their EventHandler_onCheckDiscretion_LivingVisibilityEvent that they fire when tempting Honey Slimes with their food item. Please report the issue to them so they can address it properly. Nothing I can do on my end.

**Comment by TelepathicGrunt** [comment] 2022-07-16 03:13
Gonna leave this up so others can see if they get the same crash until corail tombstone fixes the issue

**Comment by TelepathicGrunt** [comment] 2022-07-16 03:14
Looks like they know about the issue but holding off on updating their mod to fix it
https://github.com/Corail31/tombstone_lite/issues/63

**Comment by Silivek** [comment] 2022-07-16 23:08
Well that's a doozy. Thanks for the help anyways! Love the mod!

**Comment by TelepathicGrunt** [comment] 2022-07-22 02:09
Looks like this is marked as fixed in tombstone-8.0.4-1.19.jar

**Closed as completed by TelepathicGrunt** 2022-07-22 02:09 UTC
Labels: Another mod's issue
