### ISSUE TITLE
Game stuck while loading blocks

### ISSUE THREAD

**Issue by 48004800** [TelepathicGrunt/Bumblezone#242] opened 2023-04-24 05:46 UTC
The Bumblezone v6.7.13 (1.19.4 MC Forge)
forge:45.0.47 
[crash-2023-04-24_13.40.16-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/11306948/crash-2023-04-24_13.40.16-server.txt)

**Comment by TelepathicGrunt** [comment] 2023-04-24 08:10
Please give me the exact seed you used for this world. Logically, this shouldn’t be possible because I spawn entities in the dead center chunk of the region as shown here https://github.com/TelepathicGrunt/Bumblezone/blob/522221415e54722315b8e570565bc83cc412ba24/common/src/main/java/com/telepathicgrunt/the_bumblezone/world/dimension/BzChunkGenerator.java#L406

Wondering if another mod is changing the location or something of the mob. If I could have an export of the modpack and affected world, it might help me more easily reproduce along with the seed uses for the world

**Comment by 48004800** [comment] 2023-04-24 08:42
> Please give me the exact seed you used for this world. Logically, this shouldn’t be possible because I spawn entities in the dead center chunk of the region as shown here
> 
> https://github.com/TelepathicGrunt/Bumblezone/blob/522221415e54722315b8e570565bc83cc412ba24/common/src/main/java/com/telepathicgrunt/the_bumblezone/world/dimension/BzChunkGenerator.java#L406
> 
> Wondering if another mod is changing the location or something of the mob. If I could have an export of the modpack and affected world, it might help me more easily reproduce along with the seed uses for the world


I tried again.
[crash-2023-04-24_16.36.42-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/11308373/crash-2023-04-24_16.36.42-server.txt)

The text file contains a list of all mods I use.

seed: -684339644277514986

**Comment by 48004800** [comment] 2023-04-24 08:52
I used over 100 mods.
It should be directly downloadable.

https://wormhole.app/R76ol#SroOgK2xsMjQVYulTfYW6g

**Comment by TelepathicGrunt** [comment] 2023-04-24 09:34
With your mods on, I just flew over 5000 blocks in creative mode generating chunks and was unable to get the crash. Were you doing anything specific to trigger the crash?

**Comment by 48004800** [comment] 2023-04-24 09:45
> With your mods on, I just flew over 5000 blocks in creative mode generating chunks and was unable to get the crash. Were you doing anything specific to trigger the crash?

Without any special actions, I enter the hive through the Ender Pearl and move in creative mode.

**Comment by 48004800** [comment] 2023-04-24 09:47
x=-3768.01, y=45.44, z=400.17
The player's coordinates when the game crashed last time.

**Comment by TelepathicGrunt** [comment] 2023-04-24 09:59
I went to the crashing chunks in your two crashlogs and went to that coordinate you provided. I also randomly teleported around the world into many different spots. I am still not able to reproduce the crash.
![image](https://user-images.githubusercontent.com/40846040/233964012-9c7d1b89-382a-404c-8ef2-af7bce853353.png)

What mod launcher are you user? If this is on a server, what server hosting are you using and you aren't using a hybrid system like mohist right? Do you have any datapacks on?

**Comment by 48004800** [comment] 2023-04-24 10:02
> I went to the crashing chunks in your two crashlogs and went to that coordinate you provided. I also randomly teleported around the world into many different spots. I am still not able to reproduce the crash. ![image](https://user-images.githubusercontent.com/40846040/233964012-9c7d1b89-382a-404c-8ef2-af7bce853353.png)
> 
> What mod launcher are you user? If this is on a server, what server hosting are you using and you aren't using a hybrid system like mohist right? Do you have any datapacks on?

I use Minecraft launcher.

I play in single player mode.

**Comment by 48004800** [comment] 2023-04-24 10:10
https://wormhole.app/lql0R#wURjAk206HTWFnyK5_TGmA
Config folder

**Comment by 48004800** [comment] 2023-04-24 10:21
I roughly understand the problem.
I'm trying to solve it myself.

**Comment by 48004800** [comment] 2023-04-24 10:29
[config.zip](https://github.com/TelepathicGrunt/Bumblezone/files/11309388/config.zip)

**Comment by TelepathicGrunt** [comment] 2023-04-24 11:08
Try this jar that is in this zip file. See if this stops the crash for good. I might had identified the cause
[the_bumblezone-6.7.14-beta+1.19.4-forge.jar.zip](https://github.com/TelepathicGrunt/Bumblezone/files/11309761/the_bumblezone-6.7.14-beta%2B1.19.4-forge.jar.zip)

**Comment by 48004800** [comment] 2023-04-24 11:58
> Try this jar that is in this zip file. See if this stops the crash for good. I might had identified the cause [the_bumblezone-6.7.14-beta+1.19.4-forge.jar.zip](https://github.com/TelepathicGrunt/Bumblezone/files/11309761/the_bumblezone-6.7.14-beta%2B1.19.4-forge.jar.zip)

It seems to have solved the problem

**Comment by TelepathicGrunt** [comment] 2023-04-26 00:07
v6.7.14 is now released with fix. Thank you for the report!

**Closed as completed by TelepathicGrunt** 2023-04-26 00:07 UTC
Labels: bug, Need more info
