### ISSUE TITLE
Crash with structure spacing with an unknown mod

### ISSUE THREAD

**Issue by madkort** [TelepathicGrunt/Bumblezone#83] opened 2021-10-12 00:44 UTC
Hello, devs.

It seems like I'm experincing some world gen issues while playing the game with your mod.
I think either bumblezone or terraforged is the issue. So I'll report error code for both devs, ty.

Description: Exception in server tick loop

```
java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.world.gen.settings.StructureSeparationSettings.func_236675_d_(SourceFile:11) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance.lambda$ap3$6(RecordCodecBuilder.java:286) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.encode(RecordCodecBuilder.java:112) ~[?:?] {re:classloading}
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96) ~[?:?] {re:classloading}
	at com.mojang.serialization.Encoder$1.encode(Encoder.java:25) ~[?:?] {re:classloading}
	at com.mojang.serialization.Codec$2.encode(Codec.java:76) ~[?:?] {re:classloading}
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.BaseMapCodec.encode(BaseMapCodec.java:52) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.SimpleMapCodec.encode(SimpleMapCodec.java:53) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.SimpleMapCodec.encode(SimpleMapCodec.java:20) ~[?:?] {re:classloading}
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96) ~[?:?] {re:classloading}
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.FieldEncoder.encode(FieldEncoder.java:24) ~[?:?] {re:classloading}
	at com.mojang.serialization.MapCodec$1.encode(MapCodec.java:39) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$4.encode(RecordCodecBuilder.java:223) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.encode(RecordCodecBuilder.java:112) ~[?:?] {re:classloading}
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96) ~[?:?] {re:classloading}
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.FieldEncoder.encode(FieldEncoder.java:24) ~[?:?] {re:classloading}
	at com.mojang.serialization.MapCodec$1.encode(MapCodec.java:39) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$8.encode(RecordCodecBuilder.java:376) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$8.encode(RecordCodecBuilder.java:380) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.encode(RecordCodecBuilder.java:112) ~[?:?] {re:classloading}
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.WorldGenSettingsExport.func_241811_a_(SourceFile:35) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.registry.RegistryKeyCodec.encode(SourceFile:42) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.RegistryKeyCodec.encode(SourceFile:13) ~[?:?] {re:classloading}
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.FieldEncoder.encode(FieldEncoder.java:24) ~[?:?] {re:classloading}
	at com.mojang.serialization.MapCodec$1.encode(MapCodec.java:39) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$6.encode(RecordCodecBuilder.java:297) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.encode(RecordCodecBuilder.java:112) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.KeyDispatchCodec.encode(KeyDispatchCodec.java:92) ~[?:?] {re:classloading}
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96) ~[?:?] {re:classloading}
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.FieldEncoder.encode(FieldEncoder.java:24) ~[?:?] {re:classloading}
	at com.mojang.serialization.MapCodec$1.encode(MapCodec.java:39) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$4.encode(RecordCodecBuilder.java:223) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.encode(RecordCodecBuilder.java:112) ~[?:?] {re:classloading}
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96) ~[?:?] {re:classloading}
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.BaseMapCodec.encode(BaseMapCodec.java:52) ~[?:?] {re:classloading}
	at net.minecraftforge.common.LenientUnboundedMapCodec.encode(LenientUnboundedMapCodec.java:75) ~[forge:?] {re:classloading}
	at net.minecraftforge.common.LenientUnboundedMapCodec.encode(LenientUnboundedMapCodec.java:22) ~[forge:?] {re:classloading}
	at com.mojang.serialization.Encoder$1.encode(Encoder.java:25) ~[?:?] {re:classloading}
	at com.mojang.serialization.Codec$2.encode(Codec.java:76) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.SimpleRegistryCodec.encode(SourceFile:28) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.SimpleRegistryCodec.encode(SourceFile:11) ~[?:?] {re:classloading}
	at com.mojang.serialization.Encoder$1.encode(Encoder.java:25) ~[?:?] {re:classloading}
	at com.mojang.serialization.Codec$2.encode(Codec.java:76) ~[?:?] {re:classloading}
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.FieldEncoder.encode(FieldEncoder.java:24) ~[?:?] {re:classloading}
	at com.mojang.serialization.MapCodec$1.encode(MapCodec.java:39) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$6.encode(RecordCodecBuilder.java:296) ~[?:?] {re:classloading}
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.encode(RecordCodecBuilder.java:112) ~[?:?] {re:classloading}
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96) ~[?:?] {re:classloading}
	at com.mojang.serialization.Encoder$1.encode(Encoder.java:25) ~[?:?] {re:classloading}
	at com.mojang.serialization.Codec$2.encode(Codec.java:76) ~[?:?] {re:classloading}
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[?:?] {re:classloading}
	at net.minecraft.world.storage.ServerWorldInfo.func_237370_a_(SourceFile:250) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.storage.ServerWorldInfo.func_230411_a_(SourceFile:231) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.storage.SaveFormat$LevelSave.func_237288_a_(SaveFormat.java:341) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:540) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:the_bumblezone.mixins.json:entities.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:807) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:the_bumblezone.mixins.json:entities.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:the_bumblezone.mixins.json:entities.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:the_bumblezone.mixins.json:entities.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}
```

**Comment by TelepathicGrunt** [comment] 2021-10-12 01:00
I dont think it is something on bumblezone's end but that log isn't very helpful sadly. I tested with terraforged and the world seems to load just fine.
![image](https://user-images.githubusercontent.com/40846040/136872918-6573c9fc-8261-4259-8381-19f535682605.png)

If you can, could you share your modpack with me? Preferably, the modpack profile (curseforge and some launchers let you export it to share the modpack). If not possible, how about zipping up the mod folder and sending that to me or giving me the list of mods you have on? That way I can download all the mods and test to see which mod could be conflicting

**Comment by madkort** [comment] 2021-10-12 01:44
I'm running it on forge-1.16.5-36.2.8 server, probably this is the case?

**Comment by TelepathicGrunt** [comment] 2021-10-12 01:53
Forge itself wouldn't cause that crash. I really would need to have the modpack in order to narrow down what is happening. No rush tho. Just give me the modpack when you got time and are able to.

**Comment by madkort** [comment] 2021-10-12 02:29
https://dropmefiles.com/2p2jW

**Comment by madkort** [comment] 2021-10-12 02:33
Server crash happens after 5-10 mins of playing / flying in the overworld.

**Comment by TelepathicGrunt** [comment] 2021-10-12 17:00
Weird. I updated bumblezone in your modlist to latest and then spent an hour flying around/teleporting to a ton of structures but I couldn't not get a crash to occur  
![image](https://user-images.githubusercontent.com/40846040/136998503-0dea3fa7-45ac-4986-99d0-54628ad4792a.png)

Maybe there's a bad config setting? Can you send me your config folder so I can test with your configs so we can rule that out or confirm if it is that.

**Comment by TelepathicGrunt** [comment] 2021-10-25 22:17
Are you still having the issue or did you figure it out? if not, can you send me you configs and datapack folders? Otherwise, I'll close this report in a few days due to being unable to reproduce the issue

**Comment by TelepathicGrunt** [comment] 2021-11-04 16:53
Due to inactivity and inability for me to reproduce this bug, I'm gonna close this issue report. Just respond if you are still having the issue with the info i need and I'll re-open this report

**Closed as completed by TelepathicGrunt** 2021-11-04 16:53 UTC
Labels: Need more info
