### ISSUE TITLE
Bumblezone overwrites bee sizes from Realistic Bees mod

### ISSUE THREAD

**Issue by Steampunkgears** [TelepathicGrunt/Bumblezone#178] opened 2022-12-13 18:22 UTC
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.1.85
Environment: Singleplayer / Multiplayer

Hi there, I was curious if there is a setting in your configs somewhere that controls the size of the regular bee's? Not sure how much trouble this will be but I was trying to figure away to use both yours and Realistic Bee's mods. I appreciate your time with this.

**Comment by Steampunkgears** [comment] 2022-12-13 18:44
Nvm I found that is was the render option in client config

**Comment by TelepathicGrunt** [comment] 2022-12-13 18:46
Oh fyi, this incompat was fixed in 1.19.2 Bumblezone already. The issue is Bumblezone’s renderer overrode Realistic Bee’s. There isn’t a config option to turn off Bumblezone’s render.

**Closed as completed by TelepathicGrunt** 2022-12-13 18:46 UTC
Labels: Unsupported versions

**Comment by Steampunkgears** [comment] 2022-12-13 19:31
Wait really I just went into the client config  for 1.18.2 and changed

"Enable lgbt+ bee renderer" = false

This ended up fixing at least the size issue.

**Comment by TelepathicGrunt** [comment] 2022-12-13 19:32
Huh. Guess I did set it up where the config turned off the renderer then

**Comment by Steampunkgears** [comment] 2022-12-13 19:33
Im just glad that it was there. Thanks for having the foresight then. I know some pains all to well as I am a game dev for my own game in ue4.
