### ISSUE TITLE
Instant Crash with Bumblezone, unsure why 1.18.1 forge

### ISSUE THREAD

**Issue by zachsai** [TelepathicGrunt/Bumblezone#93] opened 2021-12-19 22:54 UTC
https://pastebin.com/CVkxD1eJ
Disabling optifine fixed the crash, so please look into the optifine incompatibility! :D

**Comment by TelepathicGrunt** [comment] 2021-12-19 22:56
Duplicate of this pinned issue report. Basically, I am not supporting Optifine lol. It’s a broken mod that needs to cease existing for the good of the entire modding community lol. There’s nothing I can do on my end to fix it 

https://github.com/TelepathicGrunt/Bumblezone/issues/92

**Closed as completed by TelepathicGrunt** 2021-12-19 22:56 UTC
Labels: duplicate

**Comment by zachsai** [comment] 2021-12-19 22:58
Bummer, I guess bumblezone for 1.18.1 will be a no go anymore, rip

**Comment by TelepathicGrunt** [comment] 2021-12-19 23:00
Or you could look into Optifine alternatives lol. Performance wise, I heard good things about magnesium for some people. For shaders, there are some shader mods in the works to replace Optifine once and for all

**Comment by zachsai** [comment] 2021-12-19 23:01
I dont use the shaders all that much, but for forge, its one of the only performance mods that exist, so I do not have much of a choice, optifine is just a must have for minecraft in my eyes
