### ISSUE TITLE
dimension not working 

### ISSUE THREAD

**Issue by siriamelis** [TelepathicGrunt/Bumblezone#218] opened 2023-03-01 13:04 UTC
modpack 1.19.3,when i try to teleport to the dimension nothing happens except for the advancement. i tried in different worlds too and nothing works. also tried with commands,still nothing. playing on forge btw

**Comment by TelepathicGrunt** [comment] 2023-03-01 14:24
I’m going to need more info. If you do `\execute in`, does the Bumblezone dimension show up in autocomplete? If not, the dimension was not made and I would urge you to go to the main menu, click on Mods button, and verify that Bumblezone is actually running. 

And is this on a server or single player? And what exact version of Bumblezone are you running and what other mods are on as well?

**Comment by siriamelis** [comment] 2023-03-02 09:47
hi,nope it doesnt autocomplete,the mod is running,also other features work, like bees in pijamas. im playing in singleplayer,version 6.6.11. (forge 44.1.20) im using some other mods but i dont think any of them are interacting (alexs mobs,aquaculture2,biomesOplenty,doggy talents,jei,natures compass,simple farming,ferritecore,terra blender,waystones)

**Comment by TelepathicGrunt** [comment] 2023-03-02 11:51
Are you actually sure you grabbed the Bumblezone jar and that the mod is actually running? Like go to the main menu, click on Mods, and look for Bumblezone there. If it is not there, you are not running the mod. I just tested and it works for me.

**Comment by siriamelis** [comment] 2023-03-03 14:12
yep..checked rn and its there. idk whats happening tbh

**Comment by TelepathicGrunt** [comment] 2023-03-03 14:54
Send me the full modded instance with the mods, configs, and world itself so I can see everything correctly. You can use google drive or Dropbox or whatever to share it.

**Comment by TelepathicGrunt** [comment] 2023-03-10 21:39
Since it’s been over a week with no one else getting the same issue and the mod instance with mods and configs not given to me, I’ll close this. After all, without a way to reproduce this myself and no one else having the issue, I can’t do anything.

**Closed as completed by TelepathicGrunt** 2023-03-10 21:39 UTC
Labels: Need more info
