### ISSUE TITLE
bumblezone biomes spawning in the end on a server

### ISSUE THREAD

**Issue by benbenlaw** [TelepathicGrunt/Bumblezone#56] opened 2021-03-05 09:25 UTC
on a server the end is filled with bumblezone biomes
![image](https://user-images.githubusercontent.com/42780877/110095376-c3e30900-7d94-11eb-8402-fa6071997d9a.png)

**Comment by TelepathicGrunt** [comment] 2021-03-05 13:03
This is sadly not an issue I can fix as I do not touch the end at all. It seems you have an end overhaul mod on that is grabbing Bumblezone’s biomes when it should not be. You should contact whatever end mod you have on to let that dev know their biome source is broken and needs tweaking. 

But just wondering, what end mods you have on?

**Comment by benbenlaw** [comment] 2021-03-05 14:53
outer ends and endergetic

**Comment by GiantLuigi4** [comment] 2021-03-05 15:15
What the

**Comment by GiantLuigi4** [comment] 2021-03-05 15:16
Only thing I can think to ask is if the bumble zone biomes are marked as end boomes?

**Comment by TelepathicGrunt** [comment] 2021-03-05 15:18
@GiantLuigi4 nope
<https://github.com/TelepathicGrunt/Bumblezone/blob/e3b841af9d7b55d8ddf363aee6f045a7839188fb/src/main/resources/data/the_bumblezone/worldgen/biome/sugar_water_floor.json#L6>

My biomes are None type which make it stranger. It could be someone's biome source is broken in such a way that they return the world int biome ID from the layers which then is resolved to my biome. Commonly caused by people not using the dynamicregistry for biomes in their layers

**Comment by GiantLuigi4** [comment] 2021-03-05 15:20
Yeah even if they were marked as end biomes, I don’t think abnormals core would automatically add them to the biome pool. Pretty sure you need to manually register them for generation with abnormals.

**Comment by benbenlaw** [comment] 2021-03-05 15:29
tried chocolate fix as well and it didnt work

**Comment by TelepathicGrunt** [comment] 2021-03-05 15:31
The reason chocolate didnt work is because this isn't a biome shuffling issue. That only happens for existing chunks and all a biome shuffling affects is the biome's colors and mob spawns. Not actual biome generation.

I cant reproduce this myself tho with endergetic, outer end, and bumblezone on. Are you able to export your modlist entirely? maybe another mod is needed to be on in order for this conflict to occur?

**Comment by GiantLuigi4** [comment] 2021-03-05 15:33
On the third issue opened relating to this, it does say on servers

**Comment by benbenlaw** [comment] 2021-03-05 15:33
https://www.curseforge.com/minecraft/modpacks/skyopolis-4

this mod pack, the end in single player works fine its only on servers

**Comment by benbenlaw** [comment] 2021-03-05 15:41
ok so with only thoose 3 mods bumblezone, enderic expansions and outerends the bug still happens

**Comment by TelepathicGrunt** [comment] 2021-03-05 15:46
No I believe you. I just cant seem to make the bug happen on my own server which is weird. Bugs that only occur randomly is a pain to debug. Hopefully Abnormal Core can figure out the cause
![image](https://user-images.githubusercontent.com/40846040/110138548-17a71f80-7da0-11eb-815c-558e0ba7b53b.png)

**Comment by benbenlaw** [comment] 2021-03-05 15:49
its super strange, the outer ends biomes and the endergetic biomes do not spawn

**Comment by benbenlaw** [comment] 2021-03-05 15:50
however these do
![image](https://user-images.githubusercontent.com/42780877/110138967-73869e00-7dca-11eb-9209-b180e3a07439.png)

**Comment by TelepathicGrunt** [comment] 2021-03-05 15:50
Looks like bagel linked you a ATM6 post about Forge updating and all. What version of Forge are you using for the server?

**Comment by benbenlaw** [comment] 2021-03-05 15:51
36.0.39 i can try updating it

**Comment by TelepathicGrunt** [comment] 2021-03-05 15:51
Hmm. Your forge version isnt the issue then. And you are making a new world to test the end each time right?

**Comment by benbenlaw** [comment] 2021-03-05 15:52
yep

**Comment by TelepathicGrunt** [comment] 2021-03-05 15:55
Here's a long shot. No idea if this will work but lets give it a try. Delete your config folder on the server so that it resets back to defaults. Maybe a broken config is doing this?

**Comment by benbenlaw** [comment] 2021-03-05 15:56
of the bumblezone or all of them

**Comment by TelepathicGrunt** [comment] 2021-03-05 15:57
All the configs. You can move the entire config folder to a different place as temporary storage if you dont want to nuke it entirely

**Comment by benbenlaw** [comment] 2021-03-05 16:00
ok

**Comment by benbenlaw** [comment] 2021-03-05 16:05
so i did have a default config for the bumble zone

**Comment by benbenlaw** [comment] 2021-03-05 16:08
but everything removed still happening

**Comment by TelepathicGrunt** [comment] 2021-03-05 16:09
Dang. That was my last suggestion. I got nothing now. Wtf is going on?

I’m curious tho, if you swap Bumblezone for The Undergarden mod, does The Undergarden biomes spawn in the end instead of bumblezone’s?

**Comment by benbenlaw** [comment] 2021-03-05 16:11
do you want me to test lol?

**Comment by benbenlaw** [comment] 2021-03-05 16:11
![image](https://user-images.githubusercontent.com/42780877/110141830-720aa500-7dcd-11eb-9558-9e4ca6cea4a6.png)

**Comment by GiantLuigi4** [comment] 2021-03-05 16:12
https://github.com/TelepathicGrunt/Bumblezone/issues/56#issuecomment-791504921 Those things are not a biome, they just generate sometimes

**Comment by TelepathicGrunt** [comment] 2021-03-05 16:12
You can test if you want but I think you did more than enough work already on this lol. Still, it’s annoying I can’t get it to happen myself.

**Comment by benbenlaw** [comment] 2021-03-05 16:13
but they still can be found without the bumblezone mod installed

**Comment by GiantLuigi4** [comment] 2021-03-05 16:15
If you were to make a vanilla worldgen datapack which just adds a single biome, would the same thing occur?

**Comment by TelepathicGrunt** [comment] 2021-03-05 16:18
here's a datapack that has 60+ new biomes (I just took the vanilla worldgen pack and change the minecraft folder to custom so now it is "custom:badlands" and all to make new biomes) 
[testworldgenpack.zip](https://github.com/TelepathicGrunt/Bumblezone/files/6091757/testworldgenpack.zip)

**Comment by benbenlaw** [comment] 2021-03-05 16:22
where does it go inside the worlds data pack?

**Comment by benbenlaw** [comment] 2021-03-05 16:27
![image](https://user-images.githubusercontent.com/42780877/110143940-b303b900-7dcf-11eb-940a-3c2a1f88f8e7.png)
working???

**Comment by TelepathicGrunt** [comment] 2021-03-05 16:28
Just checked and the modpack is indeed using the latest abnormals core, endergetic, and bumblezone. Outer end is 4 versions behind but i doubt the issue is caused by that.

Where are you running the server on? Some places like Mohist is know to wreck mods

**Comment by benbenlaw** [comment] 2021-03-05 16:29
bisect hosting is the main server but im testing by running a server off home pc

**Comment by TelepathicGrunt** [comment] 2021-03-05 16:29
Ok so server is fine

**Comment by TelepathicGrunt** [comment] 2021-03-05 16:33
This is the absolutely last thing I can think of. Try this bumblezone jar. I registered my biomes at mod startup with dummy biomes and the json overrides it later.
[the_bumblezone-1.16.5-2.2.16b.zip](https://github.com/TelepathicGrunt/Bumblezone/files/6091840/the_bumblezone-1.16.5-2.2.16b.zip)

If this jar work, then something in abnormals isn't working properly I think for code biomes being overriden by json biomes. Which is a problem as some people do this to make json biomes spawn in the overworld with forge's BiomeManager hook. And over course, people using datapacks too to override biomes.

If this jar doesnt work, I'm am gonna get a drink of water and walk away from this cursed issue report lmao

**Comment by benbenlaw** [comment] 2021-03-05 16:37
trying now

**Comment by benbenlaw** [comment] 2021-03-05 16:39
well well well its working

**Comment by benbenlaw** [comment] 2021-03-05 16:40
i deleted the end and added the updated mod and its also working on the server as well

**Comment by TelepathicGrunt** [comment] 2021-03-05 16:41
yep then it's a registry issue in abnormal's end biome provider layer most likely. Issue probably would occur with many other mods that uses dummy biomes to spawn json biomes in the overworld.

**Comment by benbenlaw** [comment] 2021-03-05 16:42
![image](https://user-images.githubusercontent.com/42780877/110145820-bdbf4d80-7dd1-11eb-9b68-869f76b68025.png)
the new generation in the box overridding the old map seems all good thanks :)

**Comment by TelepathicGrunt** [comment] 2021-03-05 16:47
I know what the issue is @GiantLuigi4 
They need to override this method and swap the biome parsing inside to use the dynamic register passed in first before trying to resolve the biome with BiomeRegistry.getKeyFromID. 

that issue caused me so much pain in bumblezone which is why I fixed it by making my own sampling method
https://github.com/TelepathicGrunt/Bumblezone/blob/dffbeb56a6f1deb87a7b0febb08d84c871d7d2d9/src/main/java/com/telepathicgrunt/the_bumblezone/dimension/BzBiomeProvider.java#L102-L114

**Comment by TelepathicGrunt** [comment] 2021-03-23 18:32
Closing now as latest Abnormals Core update has fixed the issue!

**Closed by TelepathicGrunt** 2021-03-23 18:32 UTC
Labels: Mod Compat issue, Won’t fix/can’t fix
