### ISSUE TITLE
Blocks does not have any assigned mining tool (MC 1.20.4)

### ISSUE THREAD

**Issue by Nova-Katt** [TelepathicGrunt/Bumblezone#384] opened 2024-05-15 21:54 UTC
I am playing 1.20.4 with the Fabric Loader, and I've noticed that none of the blocks I've found so far can be mined faster with any tool whatsoever.
Doesn't matter if it's a pickaxe, axe, shovel, sword, hoe, shears or just my hand. It's the same speed anyway.
This makes the dimension incredibly frustrating when there is no tool that can speed up digging around in there.
Netherite or Efficiency enchantment does nothing, so I could as well just mine things with my empty hand, which takes many seconds per block.
I also haven't found any mod-related items that mines stuff faster either.

Is this intentional? Or is it just a forgotten code to give the blocks their assigned tool? :)

**Comment by TelepathicGrunt** [comment] 2024-05-15 21:56
I use the same settings as honeycomb blocks which is all tools are the right tool. Just slower. Which is why I added the Comb Cutter enchantment you can put on your Shears or Swords to mine any honeycomb or wax blocks super fast. It is a common enchant you can get from enchanting tables.

**Comment by TelepathicGrunt** [comment] 2024-05-15 21:58
When you say many seconds per block though, can you please tell me EXACTLY what block you’re mining that is taking that long? Only like Ancient Wax should be that kind of slow if not comb cutter and have not consumed Essence of the bees. Or was the many seconds an exaggeration of mining the normal vanilla honeycombs or my porous honeycomb blocks?

**Comment by TelepathicGrunt** [comment] 2024-05-18 19:25
Tested Fabric 1.20.4 and everything seems to be working as intended. Roughly vanilla comb mining speed with carvable wax slightly faster and ancient wax slower. And Comb Cutter enchantment mines them all super fast

https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/a07760a5-553b-4ab7-b515-e6ee04b842ac

Closing now. Let me know if the mining speeds you're seeing do not match this video. If it doesn't match, please give me the modpack you are using.

**Closed as completed by TelepathicGrunt** 2024-05-18 19:25 UTC
