### ISSUE TITLE
Server crash after rendering hanging garden chunk (?)

### ISSUE THREAD

**Issue by AmayaValkyria** [TelepathicGrunt/Bumblezone#216] opened 2023-02-25 20:05 UTC
Hello there,

A friend and I have a small Minecraft server where this mod is also installed. Today I was walking through the Bumblezone and at some point the server crashed and we couldn't connect anymore. The crash report from the server says the following at line 94:

`-- Feature --
Details:
	Description: ResourceKey[minecraft:worldgen/structure / the_bumblezone:hanging_garden]`

and at line 144:

`-- Chunk to be generated --
Details:
	Location: -81,-130
	Position hash: -554050781265
	Generator: com.telepathicgrunt.the_bumblezone.world.dimension.BzChunkGenerator@790d9409`

It looks like it tried to load a hanging garden and crashed. 

I have attached the complete crash report here.

I think your mod is very great and would be happy to see more of it. I was very happy when I found out about the Bumblezone. 😊 

Thank you very much for looking at it.
Kind regards

[crash-2023-02-25_18.50.51-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/10832193/crash-2023-02-25_18.50.51-server.txt)

**Comment by TelepathicGrunt** [comment] 2023-02-25 20:07
Basically a duplicate of this: https://github.com/TelepathicGrunt/Bumblezone/issues/210

Short summary, Biome Makeover Moth is not safe to spawn in worldgen. Better minecraft/medieval minecraft modpacks still hasn’t updated to fix the issue. Workaround is to update Bumblezone where I removed the moth from my hanging gardens entity spawning tag. Or you can click link above and download the workaround datapack onto your server if you are unable to update the mod

**Closed as completed by TelepathicGrunt** 2023-02-25 20:07 UTC
Labels: duplicate
