### ISSUE TITLE
Bumblezone crashing error 

### ISSUE THREAD

**Issue by zackcb01** [TelepathicGrunt/Bumblezone#214] opened 2023-02-24 23:57 UTC
Bumblezone crashing server current when people try to go in a certain area of it. 

[25.02 00:45:45] [Server] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for the_bumblezone:the_bumblezone
[25.02 00:45:45] [Server] net.minecraft.class_Feature placement
[25.02 00:45:45] [Server] 	at net.minecraft.class_3898.method_39934(class_3898.java:693) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:557) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:566) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3215.method_19492(class_3215.java:279) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at java.lang.Thread.run(Thread.java:833) [?:?]
[25.02 00:45:45] [Server] Caused byjava.util.ConcurrentModificationException: ThreadLocalRandom accessed from a different thread (owner: Thread[Server thread,8,main], current: Thread[Worker-Main-1,5,main])
[25.02 00:45:45] [Server] 	at com.ishland.uwrad.common.CheckedThreadLocalRandom.method_43156(CheckedThreadLocalRandom.java:32) ~[unsafe-world-random-access-detector-1.0.0.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_6566.method_43048(class_6566.java:33) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at party.lemons.biomemakeover.entity.MothEntity$MoveToLightGoal.<init>(MothEntity.java:296) ~[biomemakeover-FABRIC-1.19.2-1.6.2.jar:?]
[25.02 00:45:45] [Server] 	at party.lemons.biomemakeover.entity.MothEntity.method_5959(MothEntity.java:74) ~[biomemakeover-FABRIC-1.19.2-1.6.2.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_1308.<init>(class_1308.java:150) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_1314.<init>(class_1314.java:14) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_1588.<init>(class_1588.java:31) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at party.lemons.biomemakeover.entity.MothEntity.<init>(MothEntity.java:61) ~[biomemakeover-FABRIC-1.19.2-1.6.2.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_1299.method_5883(class_1299.java:487) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at com.telepathicgrunt.the_bumblezone.world.features.HangingGardenMob.method_13151(HangingGardenMob.java:42) ~[the_bumblezone_fabric-6.6.7+1.19.2.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3031.method_40163(class_3031.java:165) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_2975.method_12862(class_2975.java:27) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_6796.method_39646(class_6796.java:56) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
[25.02 00:45:45] [Server] 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_6796.method_39648(class_6796.java:55) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_6796.method_39644(class_6796.java:40) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3776.method_16626(class_3776.java:75) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3790.method_27236(class_3790.java:89) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3790.method_14931(class_3790.java:85) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3449.method_14974(class_3449.java:99) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_2794.method_38265(class_2794.java:429) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_2794.method_12102(class_2794.java:428) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_2806.method_20613(class_2806.java:145) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_2806.method_12154(class_2806.java:292) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3898.method_17225(class_3898.java:679) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
[25.02 00:45:45] [Server] 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3846.run(class_3846.java:102) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
[25.02 00:45:45] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
[25.02 00:45:45] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
[25.02 00:45:45] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
[25.02 00:45:45] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
[25.02 00:45:45] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[25.02 00:45:45] [Server] [Server thread/ERROR]: Encountered an unexpected exception
[25.02 00:45:45] [Server] net.minecraft.class_Feature placement
[25.02 00:45:45] [Server] 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at java.lang.Thread.run(Thread.java:833) [?:?]
[25.02 00:45:45] [Server] Caused byjava.util.ConcurrentModificationException: ThreadLocalRandom accessed from a different thread (owner: Thread[Server thread,8,main], current: Thread[Worker-Main-1,5,main])
[25.02 00:45:45] [Server] 	at com.ishland.uwrad.common.CheckedThreadLocalRandom.method_43156(CheckedThreadLocalRandom.java:32) ~[unsafe-world-random-access-detector-1.0.0.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_6566.method_43048(class_6566.java:33) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at party.lemons.biomemakeover.entity.MothEntity$MoveToLightGoal.<init>(MothEntity.java:296) ~[biomemakeover-FABRIC-1.19.2-1.6.2.jar:?]
[25.02 00:45:45] [Server] 	at party.lemons.biomemakeover.entity.MothEntity.method_5959(MothEntity.java:74) ~[biomemakeover-FABRIC-1.19.2-1.6.2.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_1308.<init>(class_1308.java:150) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_1314.<init>(class_1314.java:14) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_1588.<init>(class_1588.java:31) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at party.lemons.biomemakeover.entity.MothEntity.<init>(MothEntity.java:61) ~[biomemakeover-FABRIC-1.19.2-1.6.2.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_1299.method_5883(class_1299.java:487) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at com.telepathicgrunt.the_bumblezone.world.features.HangingGardenMob.method_13151(HangingGardenMob.java:42) ~[the_bumblezone_fabric-6.6.7+1.19.2.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3031.method_40163(class_3031.java:165) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_2975.method_12862(class_2975.java:27) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_6796.method_39646(class_6796.java:56) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
[25.02 00:45:45] [Server] 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_6796.method_39648(class_6796.java:55) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_6796.method_39644(class_6796.java:40) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3776.method_16626(class_3776.java:75) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3790.method_27236(class_3790.java:89) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3790.method_14931(class_3790.java:85) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3449.method_14974(class_3449.java:99) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_2794.method_38265(class_2794.java:429) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_2794.method_12102(class_2794.java:428) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_2806.method_20613(class_2806.java:145) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_2806.method_12154(class_2806.java:292) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3898.method_17225(class_3898.java:679) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
[25.02 00:45:45] [Server] 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[server-intermediary.jar:?]
[25.02 00:45:45] [Server] 	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[server-intermediary.jar:?]

**Comment by TelepathicGrunt** [comment] 2023-02-25 00:00
This is a duplicate of this issue report since Better Minecraft still has not updated their modpack: https://github.com/TelepathicGrunt/Bumblezone/issues/210

Here's the explanation for what the issue actually is: https://github.com/TelepathicGrunt/Bumblezone/issues/210#issuecomment-1438779449

Either update Bumblezone where I removed the Biome Makeover Moth from the entity tag I use for spawning mobs in Hanging Gardens structures. Or use the datapack in the link above if you cannot update Bumblezone

**Closed as completed by TelepathicGrunt** 2023-02-25 00:00 UTC
Labels: duplicate, Another mod's issue

**Comment by zackcb01** [comment] 2023-02-25 00:05
This was with the medievalmc pack. Thanks for the response!

**Comment by TelepathicGrunt** [comment] 2023-02-25 00:07
It's still the same issue as the Lunar Studio team includes Bumblezone, Biome Makeover, and C2ME in both Better Minecraft and Medieval MC but still have not yet updated to fix the crash. Forcing users to do the workarounds themselves.

The line from your log that shows the source of the issue:

![image](https://user-images.githubusercontent.com/40846040/221323565-908e6abd-646e-4a4d-b78e-b5090610be18.png)

**Comment by zackcb01** [comment] 2023-02-25 00:14
Gotcha! Used the fix described above! Didn't know if it would make a difference or not.
