### ISSUE TITLE
crash when Rendering Entity Type: the_bumblezone:bee_queen

### ISSUE THREAD

**Issue by Roureland** [TelepathicGrunt/Bumblezone#217] opened 2023-02-26 08:44 UTC
Hello, I created a GitHub account specifically to thank you for your work, "bumblezone" is the most impressive mod I've ever seen, we love it. Unfortunately, the latest version for 1.19.3 crashes the world when rendering the Bee_queen. maybe it's due to the interaction with another mod or something like that maybe it happens to more people, I can provide the information you require.
Anyway...GREAT JOB. we admire you
[crash-2023-02-26_09.14.57-client.txt](https://github.com/TelepathicGrunt/Bumblezone/files/10833283/crash-2023-02-26_09.14.57-client.txt)

**Comment by TelepathicGrunt** [comment] 2023-02-26 11:09
What in the world is this crashlog? It looks like it is completely missing the part that actually reports the crashing code? I’m not even sure how that is possible what??

Hmm. Can you reproduce the crash and then share the latest.log file instead from the logs folder above the mods folder? If not, I’ll try and put on all your mods and see if I can get it to happen myself

**Comment by TelepathicGrunt** [comment] 2023-02-26 12:17
Crash is caused by Sodium. Will look into solution now

**Comment by TelepathicGrunt** [comment] 2023-02-26 16:53
fixed now. Workaround is to disable the transparent item rendering on bee queen if sodium is on

**Closed as completed by TelepathicGrunt** 2023-02-26 16:53 UTC
Labels: bug, Mod Compat

**Comment by Roureland** [comment] 2023-02-26 18:44
Ty very much, Perfect, Great JOB!
