### ISSUE TITLE
[AOF 7 1.20.1] Pebblehost Server (not player client) crashes within seconds of loading into the bumblezone

### ISSUE THREAD

**Issue by jacobcshort78** [TelepathicGrunt/Bumblezone#395] opened 2024-05-22 23:36 UTC
Hello,

I'm running a server with two other friends on Pebblehost in the modpack All of Fabric 7 2.2.2 in 1.20.1, and I'm having this issue when any of load into the bumblezone that the entire server crashes. Here are all of the crash reports we've had from the issue:

https://pastebin.com/aimUy631
https://pastebin.com/f3jVsRRy
https://pastebin.com/HafYaZ92
https://pastebin.com/E6jWHZpB
https://pastebin.com/1DvAFsEK

It appears to have something to do with entities interacting with fluid, and I'm not sure if that's a known or fixed issue or whether there's a patch for it for this version. In retrospect this might be an issue for the modpack author to tackle, but if you have a fix for it as well, that'd be great.

Thanks,
Jacob

**Comment by TelepathicGrunt** [comment] 2024-05-22 23:44
Duplicate of https://github.com/TelepathicGrunt/Bumblezone/issues/390

please read that issue report for more info and what the problematic mod is

**Closed as completed by TelepathicGrunt** 2024-05-22 23:44 UTC
Labels: duplicate
