### ISSUE TITLE
Fabric 1.20.1

### ISSUE THREAD

**Issue by Nicolol1234** [TelepathicGrunt/Bumblezone#280] opened 2023-10-09 19:48 UTC
Error on startup, here is the error report:

```
[21:20:35] [Render thread/INFO]: Registering recipes...
[21:20:35] [Render thread/INFO]: Registering recipes: jei:minecraft took 216.9 milliseconds
[21:20:35] [Render thread/ERROR]: Found a broken recipe, failed to setRecipe with RecipeLayoutBuilder: Ad Astra ad_astra:conversion/oxygen_from_oxygen class earth.terrarium.ad_astra.common.recipe.OxygenConversionRecipe

java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.util.ImmutableCollections$ListN.get(Unknown Source) ~[?:?]
	at net.minecraft.class_6885$class_6887.method_40240(class_6885.java:65) ~[client-intermediary.jar:?]
	at earth.terrarium.ad_astra.common.compat.jei.category.OxygenConversionCategory.setRecipe(OxygenConversionCategory.java:45) ~[ad_astra-fabric-1.20.1-1.15.4.jar:?]
	at earth.terrarium.ad_astra.common.compat.jei.category.OxygenConversionCategory.setRecipe(OxygenConversionCategory.java:27) ~[ad_astra-fabric-1.20.1-1.15.4.jar:?]
	at mezz.jei.library.util.IngredientSupplierHelper.getIngredientSupplier(IngredientSupplierHelper.java:22) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.library.recipes.RecipeManagerInternal.lambda$addRecipes$0(RecipeManagerInternal.java:120) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(Unknown Source) ~[?:?]
	at mezz.jei.library.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:126) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.library.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:108) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.library.load.registration.RecipeRegistration.addRecipes(RecipeRegistration.java:64) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at earth.terrarium.ad_astra.common.compat.jei.AdAstraJeiPlugin.registerRecipes(AdAstraJeiPlugin.java:52) ~[ad_astra-fabric-1.20.1-1.15.4.jar:?]
	at mezz.jei.library.load.PluginLoader.lambda$createRecipeManager$10(PluginLoader.java:144) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:27) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:144) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:132) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.fabric.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:84) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.fabric.startup.ClientLifecycleHandler.lambda$registerEvents$1(ClientLifecycleHandler.java:53) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.fabric.events.JeiLifecycleEvents.lambda$static$4(JeiLifecycleEvents.java:28) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at net.minecraft.class_634.handler$dcg002$jei$handleUpdateRecipes(class_634.java:8222) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11106(class_634.java:1445) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_11997(class_2788.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_11054(class_2788.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.14.22.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
[21:20:35] [Render thread/INFO]: Registering recipes: ad_astra:jei took 75.34 milliseconds
[21:20:35] [Render thread/ERROR]: Found a broken recipe, failed to setRecipe with RecipeLayoutBuilder: com.telepathicgrunt.the_bumblezone.modcompat.recipecategories.jei.JEIQueenTradesInfo@7a37f526

java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source) ~[?:?]
	at com.telepathicgrunt.the_bumblezone.modcompat.recipecategories.jei.QueenTradesJEICategory.setRecipe(QueenTradesJEICategory.java:103) ~[the_bumblezone-7.0.16+1.20.1-fabric.jar:?]
	at com.telepathicgrunt.the_bumblezone.modcompat.recipecategories.jei.QueenTradesJEICategory.setRecipe(QueenTradesJEICategory.java:22) ~[the_bumblezone-7.0.16+1.20.1-fabric.jar:?]
	at mezz.jei.library.util.IngredientSupplierHelper.getIngredientSupplier(IngredientSupplierHelper.java:22) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.library.recipes.RecipeManagerInternal.lambda$addRecipes$0(RecipeManagerInternal.java:120) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.LinkedList$LLSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(Unknown Source) ~[?:?]
	at mezz.jei.library.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:126) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.library.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:108) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.library.load.registration.RecipeRegistration.addRecipes(RecipeRegistration.java:64) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at com.telepathicgrunt.the_bumblezone.modcompat.JEIIntegration.registerRecipes(JEIIntegration.java:103) ~[the_bumblezone-7.0.16+1.20.1-fabric.jar:?]
	at mezz.jei.library.load.PluginLoader.lambda$createRecipeManager$10(PluginLoader.java:144) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:27) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:144) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:132) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.fabric.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:84) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.fabric.startup.ClientLifecycleHandler.lambda$registerEvents$1(ClientLifecycleHandler.java:53) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.fabric.events.JeiLifecycleEvents.lambda$static$4(JeiLifecycleEvents.java:28) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at net.minecraft.class_634.handler$dcg002$jei$handleUpdateRecipes(class_634.java:8222) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11106(class_634.java:1445) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_11997(class_2788.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_11054(class_2788.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.14.22.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
[21:20:35] [Render thread/ERROR]: Found a broken recipe, failed to setRecipe with RecipeLayoutBuilder: com.telepathicgrunt.the_bumblezone.modcompat.recipecategories.jei.JEIQueenTradesInfo@3f2ed4d5

java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source) ~[?:?]
	at com.telepathicgrunt.the_bumblezone.modcompat.recipecategories.jei.QueenTradesJEICategory.setRecipe(QueenTradesJEICategory.java:103) ~[the_bumblezone-7.0.16+1.20.1-fabric.jar:?]
	at com.telepathicgrunt.the_bumblezone.modcompat.recipecategories.jei.QueenTradesJEICategory.setRecipe(QueenTradesJEICategory.java:22) ~[the_bumblezone-7.0.16+1.20.1-fabric.jar:?]
	at mezz.jei.library.util.IngredientSupplierHelper.getIngredientSupplier(IngredientSupplierHelper.java:22) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.library.recipes.RecipeManagerInternal.lambda$addRecipes$0(RecipeManagerInternal.java:120) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.LinkedList$LLSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(Unknown Source) ~[?:?]
	at mezz.jei.library.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:126) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.library.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:108) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.library.load.registration.RecipeRegistration.addRecipes(RecipeRegistration.java:64) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at com.telepathicgrunt.the_bumblezone.modcompat.JEIIntegration.registerRecipes(JEIIntegration.java:103) ~[the_bumblezone-7.0.16+1.20.1-fabric.jar:?]
	at mezz.jei.library.load.PluginLoader.lambda$createRecipeManager$10(PluginLoader.java:144) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:27) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:144) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:132) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.fabric.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:84) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.fabric.startup.ClientLifecycleHandler.lambda$registerEvents$1(ClientLifecycleHandler.java:53) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at mezz.jei.fabric.events.JeiLifecycleEvents.lambda$static$4(JeiLifecycleEvents.java:28) ~[jei-1.20.1-fabric-15.2.0.27.jar:?]
	at net.minecraft.class_634.handler$dcg002$jei$handleUpdateRecipes(class_634.java:8222) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11106(class_634.java:1445) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_11997(class_2788.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_11054(class_2788.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.14.22.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
[21:20:35] [Render thread/ERROR]: Found a broken recipe, failed to setRecipe with RecipeLayoutBuilder: com.telepathicgrunt.the_bumblezone.modcompat.recipecategories.jei.JEIQueenTradesInfo@71de4837
```

**Comment by TelepathicGrunt** [comment] 2023-10-09 20:28
I will likely need to know what modpack you are playing with in case it is how another mod's items are messing up my queen trade system. i see you're using Bumblezone 7.0.16

**Comment by TelepathicGrunt** [comment] 2023-10-17 12:20
Closing report due to a week of no additional info. Without modpack, I cannot reproduce nor fix the issue

**Closed as completed by TelepathicGrunt** 2023-10-17 12:20 UTC
Labels: Mod Compat, Need more info

**Comment by ninjaeon** [comment] 2024-05-19 05:27
I know this is a closed issue, but I had the same errors and resolved it by removing "Just Enough Farmer's Recipes" JustEnoughFarmersRecipes-1.20.1-1.0.1.jar from my Fabric 1.20.1 install with the_bumblezone-7.3.7+1.20.1-fabric.jar

Not sure if it was related, but I had EMI installed along with JEI, and it turned out that I didn't need "Just Enough Farmer's Recipes" installed anyways (the recipes were already appearing without it).

Just adding this info in case anyone else looks it up like I did.
