### ISSUE TITLE
Rendering mods + high render distance causes Bumblezone to stop rendering with default Fog Reducer config value (Better Minecraft Fabric 1.19.2)

### ISSUE THREAD

**Issue by iDRAGOO** [TelepathicGrunt/Bumblezone#193] opened 2023-01-17 20:25 UTC
hi so i am playing on multiplayer server with my friend and he have the same issue when i get close to the block it doesn't have texture even the water when i go far away it shows the texture any fix ? 
![2023-01-17_23 20 45](https://user-images.githubusercontent.com/71678272/213005138-ca2bacb5-121b-47a5-801b-f1a02dfd07cf.png)
![2023-01-17_23 24 58](https://user-images.githubusercontent.com/71678272/213005153-7feabd9d-e142-4a24-ad90-654381090201.png)

**Comment by TelepathicGrunt** [comment] 2023-01-17 20:28
Exactly what better minecraft version are you using? Are you using the exact same pack version on clientside as server? Is the server stalling or stuck (does mob stop moving and fluids not flow anymore)? 

I could not reproduce this at all last time someone asked about it so I need more info

**Comment by iDRAGOO** [comment] 2023-01-17 20:44
yes same version same pack same mod loader and no the server not stalling or stuck the console doesn't show anything and the mobs moving normally no lag or anything i can hit them and kill them and the water is flowing nothing weird but what is weird that if i go under the water i can see everything normally even the close the blocks

**Comment by TelepathicGrunt** [comment] 2023-01-17 20:45
If you know which mods are clientside rendering mods like sodium, try disabling those first to see if it is a bug in those rendering optimizing/adjusting mods

**Comment by iDRAGOO** [comment] 2023-01-17 20:47
i got the fix nvm it doesn't render correctly when its 29+ chunks in render distance mine was 32

**Comment by iDRAGOO** [comment] 2023-01-17 20:47
29 has no problems at all

**Comment by TelepathicGrunt** [comment] 2023-01-17 20:48
This is changing the render distance on clientside or serverside? Just want to double check

**Comment by iDRAGOO** [comment] 2023-01-17 20:48
clientside

**Comment by iDRAGOO** [comment] 2023-01-17 20:49
i have the serverside view distance at 32

**Comment by iDRAGOO** [comment] 2023-01-17 20:49
thanks for your fast reply i hope this helps someone

**Comment by TelepathicGrunt** [comment] 2023-01-17 23:40
I think the dimension fog is struggling at extreme render distance and then fully breaks with rendering optimizing mods put on. 

Setting the Fog Reducer to a lower value in Bumblezone's config on client side should be a workaround to allowing higher render distances. 3.25 seems to work. I will need to find a way to dynamically adjust the fog density based on extreme render distance to reduce the chance of this occurring without user config intervention but it ultimately looks like a bug with a rendering optimizing mod
![image](https://user-images.githubusercontent.com/40846040/213036123-b1cfd7e0-4d42-4b73-b79d-99e06b3a5dae.png)

**Comment by TelepathicGrunt** [comment] 2023-01-18 01:36
Issue turned out to be on my end. Bumblezone fog config and mixin was broken. Currently changing the config from fogReducer to fogThickness and should not break on large render distances with other rendering optimizing mods and unlocks farther viewing range. Next update will have this change and will apply the change in config and view automatically. 

![image](https://user-images.githubusercontent.com/40846040/213059600-3015b778-3b05-49ca-980b-f28784333c03.png)

**Comment by TelepathicGrunt** [comment] 2023-01-27 14:01
Fixed in the newest 1.19.2 bumblezone update released now.
The fix for the 1.19.3 bumblezone is coming soon.

**Comment by TelepathicGrunt** [comment] 2023-02-07 23:25
fixed now in 6.6.3 releases for 1.19.3

**Closed as completed by TelepathicGrunt** 2023-02-07 23:25 UTC
Labels: bug, Mod Compat

**Comment by P3rf3ctXZer0** [comment] 2023-09-20 23:51
This is issue has returned. the_bumblezone_forge-6.7.34+1.19.2.jar I am too drunk to give full dets but basically fog is all encompassing. I am using 1.19.2 Embeddium. (Fixes many other issues Rubidium has had for a while.) 43.2.23

**Comment by TelepathicGrunt** [comment] 2023-09-21 00:04
@P3rf3ctXZer0 Issue does not happen for me with embeddium-0.1.6+mc1.19.2.jar and the_bumblezone_forge-6.7.34+1.19.2.jar. Please verify your bumblezone client configs are set to default to make sure they are ok (or delete file so it regenerates with defaults). If issue persist, please make a new issue report with the details again and link to exact modpack you are using
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/04f5add0-fd43-4905-af58-c9f46eef470e)

**Comment by P3rf3ctXZer0** [comment] 2023-09-21 02:57
> @P3rf3ctXZer0 Issue does not happen for me with embeddium-0.1.6+mc1.19.2.jar and the_bumblezone_forge-6.7.34+1.19.2.jar. Please verify your bumblezone client configs are set to default to make sure they are ok (or delete file so it regenerates with defaults). If issue persist, please make a new issue report with the details again and link to exact modpack you are using ![image](https://user-images.githubusercontent.com/40846040/269446399-04f5add0-fd43-4905-af58-c9f46eef470e.png)

When I sober up I will do a deep dive. Thanks for testing though.
